package cn.itrip.dao;

import cn.itrip.beans.pojo.ItripUser;
import cn.itrip.beans.pojo.ItripUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ItripUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_user
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int countByExample(ItripUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_user
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int deleteByExample(ItripUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_user
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_user
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int insert(ItripUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_user
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int insertSelective(ItripUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_user
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    List<ItripUser> selectByExample(ItripUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_user
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    ItripUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_user
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int updateByExampleSelective(@Param("record") ItripUser record, @Param("example") ItripUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_user
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int updateByExample(@Param("record") ItripUser record, @Param("example") ItripUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_user
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int updateByPrimaryKeySelective(ItripUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_user
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int updateByPrimaryKey(ItripUser record);
}