package cn.itrip.dao;

import cn.itrip.beans.pojo.ItripHotel;
import cn.itrip.beans.pojo.ItripHotelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ItripHotelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int countByExample(ItripHotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int deleteByExample(ItripHotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int insert(ItripHotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int insertSelective(ItripHotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    List<ItripHotel> selectByExample(ItripHotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    ItripHotel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int updateByExampleSelective(@Param("record") ItripHotel record, @Param("example") ItripHotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int updateByExample(@Param("record") ItripHotel record, @Param("example") ItripHotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int updateByPrimaryKeySelective(ItripHotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int updateByPrimaryKey(ItripHotel record);
}