package cn.itrip.dao;

import cn.itrip.beans.pojo.ItripHotelOrder;
import cn.itrip.beans.pojo.ItripHotelOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ItripHotelOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_order
     *
     * @mbggenerated Wed May 03 09:27:28 CST 2017
     */
    int countByExample(ItripHotelOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_order
     *
     * @mbggenerated Wed May 03 09:27:28 CST 2017
     */
    int deleteByExample(ItripHotelOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_order
     *
     * @mbggenerated Wed May 03 09:27:28 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_order
     *
     * @mbggenerated Wed May 03 09:27:28 CST 2017
     */
    int insert(ItripHotelOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_order
     *
     * @mbggenerated Wed May 03 09:27:28 CST 2017
     */
    int insertSelective(ItripHotelOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_order
     *
     * @mbggenerated Wed May 03 09:27:28 CST 2017
     */
    List<ItripHotelOrder> selectByExampleWithBLOBs(ItripHotelOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_order
     *
     * @mbggenerated Wed May 03 09:27:28 CST 2017
     */
    List<ItripHotelOrder> selectByExample(ItripHotelOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_order
     *
     * @mbggenerated Wed May 03 09:27:28 CST 2017
     */
    ItripHotelOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_order
     *
     * @mbggenerated Wed May 03 09:27:28 CST 2017
     */
    int updateByExampleSelective(@Param("record") ItripHotelOrder record, @Param("example") ItripHotelOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_order
     *
     * @mbggenerated Wed May 03 09:27:28 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") ItripHotelOrder record, @Param("example") ItripHotelOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_order
     *
     * @mbggenerated Wed May 03 09:27:28 CST 2017
     */
    int updateByExample(@Param("record") ItripHotelOrder record, @Param("example") ItripHotelOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_order
     *
     * @mbggenerated Wed May 03 09:27:28 CST 2017
     */
    int updateByPrimaryKeySelective(ItripHotelOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_order
     *
     * @mbggenerated Wed May 03 09:27:28 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(ItripHotelOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_order
     *
     * @mbggenerated Wed May 03 09:27:28 CST 2017
     */
    int updateByPrimaryKey(ItripHotelOrder record);
}