package cn.itrip.dao;

import java.util.List;

import cn.itrip.beans.pojo.ItripAreaDic;
import cn.itrip.beans.pojo.ItripAreaDicExample;
import org.apache.ibatis.annotations.Param;

public interface ItripAreaDicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_area_dic
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int countByExample(ItripAreaDicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_area_dic
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int deleteByExample(ItripAreaDicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_area_dic
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_area_dic
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int insert(ItripAreaDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_area_dic
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int insertSelective(ItripAreaDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_area_dic
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    List<ItripAreaDic> selectByExample(ItripAreaDicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_area_dic
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    ItripAreaDic selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_area_dic
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int updateByExampleSelective(@Param("record") ItripAreaDic record, @Param("example") ItripAreaDicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_area_dic
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int updateByExample(@Param("record") ItripAreaDic record, @Param("example") ItripAreaDicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_area_dic
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int updateByPrimaryKeySelective(ItripAreaDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_area_dic
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int updateByPrimaryKey(ItripAreaDic record);
}