package cn.itrip.dao;

import cn.itrip.beans.pojo.ItripUserLinkUser;
import cn.itrip.beans.pojo.ItripUserLinkUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ItripUserLinkUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_user_link_User
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int countByExample(ItripUserLinkUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_user_link_User
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int deleteByExample(ItripUserLinkUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_user_link_User
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_user_link_User
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int insert(ItripUserLinkUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_user_link_User
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int insertSelective(ItripUserLinkUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_user_link_User
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    List<ItripUserLinkUser> selectByExample(ItripUserLinkUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_user_link_User
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    ItripUserLinkUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_user_link_User
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int updateByExampleSelective(@Param("record") ItripUserLinkUser record, @Param("example") ItripUserLinkUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_user_link_User
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int updateByExample(@Param("record") ItripUserLinkUser record, @Param("example") ItripUserLinkUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_user_link_User
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int updateByPrimaryKeySelective(ItripUserLinkUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_user_link_User
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int updateByPrimaryKey(ItripUserLinkUser record);
}