package cn.itrip.dao;

import cn.itrip.beans.pojo.ItripHotelKeyword;
import cn.itrip.beans.pojo.ItripHotelKeywordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ItripHotelKeywordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_keyword
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int countByExample(ItripHotelKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_keyword
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int deleteByExample(ItripHotelKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_keyword
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_keyword
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int insert(ItripHotelKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_keyword
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int insertSelective(ItripHotelKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_keyword
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    List<ItripHotelKeyword> selectByExample(ItripHotelKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_keyword
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    ItripHotelKeyword selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_keyword
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int updateByExampleSelective(@Param("record") ItripHotelKeyword record, @Param("example") ItripHotelKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_keyword
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int updateByExample(@Param("record") ItripHotelKeyword record, @Param("example") ItripHotelKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_keyword
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int updateByPrimaryKeySelective(ItripHotelKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_keyword
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int updateByPrimaryKey(ItripHotelKeyword record);
}