package cn.itrip.dao;

import cn.itrip.beans.pojo.ItripOrderLinkUser;
import cn.itrip.beans.pojo.ItripOrderLinkUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ItripOrderLinkUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_order_link_user
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int countByExample(ItripOrderLinkUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_order_link_user
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int deleteByExample(ItripOrderLinkUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_order_link_user
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_order_link_user
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int insert(ItripOrderLinkUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_order_link_user
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int insertSelective(ItripOrderLinkUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_order_link_user
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    List<ItripOrderLinkUser> selectByExample(ItripOrderLinkUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_order_link_user
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    ItripOrderLinkUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_order_link_user
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int updateByExampleSelective(@Param("record") ItripOrderLinkUser record, @Param("example") ItripOrderLinkUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_order_link_user
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int updateByExample(@Param("record") ItripOrderLinkUser record, @Param("example") ItripOrderLinkUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_order_link_user
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int updateByPrimaryKeySelective(ItripOrderLinkUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_order_link_user
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int updateByPrimaryKey(ItripOrderLinkUser record);
}