package cn.itrip.dao;

import cn.itrip.beans.pojo.ItripHotelTempStore;
import cn.itrip.beans.pojo.ItripHotelTempStoreExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ItripHotelTempStoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_temp_store
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int countByExample(ItripHotelTempStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_temp_store
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int deleteByExample(ItripHotelTempStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_temp_store
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_temp_store
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int insert(ItripHotelTempStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_temp_store
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int insertSelective(ItripHotelTempStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_temp_store
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    List<ItripHotelTempStore> selectByExample(ItripHotelTempStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_temp_store
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    ItripHotelTempStore selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_temp_store
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int updateByExampleSelective(@Param("record") ItripHotelTempStore record, @Param("example") ItripHotelTempStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_temp_store
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int updateByExample(@Param("record") ItripHotelTempStore record, @Param("example") ItripHotelTempStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_temp_store
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int updateByPrimaryKeySelective(ItripHotelTempStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_temp_store
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int updateByPrimaryKey(ItripHotelTempStore record);
}