package cn.itrip.dao;

import cn.itrip.beans.pojo.ItripLabelDic;
import cn.itrip.beans.pojo.ItripLabelDicExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ItripLabelDicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_label_dic
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int countByExample(ItripLabelDicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_label_dic
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int deleteByExample(ItripLabelDicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_label_dic
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_label_dic
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int insert(ItripLabelDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_label_dic
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int insertSelective(ItripLabelDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_label_dic
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    List<ItripLabelDic> selectByExample(ItripLabelDicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_label_dic
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    ItripLabelDic selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_label_dic
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int updateByExampleSelective(@Param("record") ItripLabelDic record, @Param("example") ItripLabelDicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_label_dic
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int updateByExample(@Param("record") ItripLabelDic record, @Param("example") ItripLabelDicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_label_dic
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int updateByPrimaryKeySelective(ItripLabelDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_label_dic
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int updateByPrimaryKey(ItripLabelDic record);
}