package cn.itrip.dao;

import cn.itrip.beans.pojo.ItripImage;
import cn.itrip.beans.pojo.ItripImageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ItripImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_image
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int countByExample(ItripImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_image
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int deleteByExample(ItripImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_image
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_image
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int insert(ItripImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_image
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int insertSelective(ItripImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_image
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    List<ItripImage> selectByExample(ItripImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_image
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    ItripImage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_image
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int updateByExampleSelective(@Param("record") ItripImage record, @Param("example") ItripImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_image
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int updateByExample(@Param("record") ItripImage record, @Param("example") ItripImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_image
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int updateByPrimaryKeySelective(ItripImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_image
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int updateByPrimaryKey(ItripImage record);
}