package cn.itrip.dao;

import cn.itrip.beans.pojo.ItripProductStore;
import cn.itrip.beans.pojo.ItripProductStoreExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ItripProductStoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_product_store
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int countByExample(ItripProductStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_product_store
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int deleteByExample(ItripProductStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_product_store
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_product_store
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int insert(ItripProductStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_product_store
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int insertSelective(ItripProductStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_product_store
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    List<ItripProductStore> selectByExample(ItripProductStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_product_store
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    ItripProductStore selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_product_store
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int updateByExampleSelective(@Param("record") ItripProductStore record, @Param("example") ItripProductStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_product_store
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int updateByExample(@Param("record") ItripProductStore record, @Param("example") ItripProductStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_product_store
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int updateByPrimaryKeySelective(ItripProductStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_product_store
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    int updateByPrimaryKey(ItripProductStore record);
}