package cn.itrip.beans.pojo;

import java.io.Serializable;
import java.util.Date;

public class ItripUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_user.id
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_user.userCode
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private String userCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_user.userPassword
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private String userPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_user.userType
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Integer userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_user.flatID
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Long flatID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_user.userName
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_user.weChat
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private String weChat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_user.QQ
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private String QQ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_user.weibo
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private String weibo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_user.baidu
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private String baidu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_user.creationDate
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_user.createdBy
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Long createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_user.modifyDate
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_user.modifiedBy
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Long modifiedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table itrip_user
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_user.id
     *
     * @return the value of itrip_user.id
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_user.id
     *
     * @param id the value for itrip_user.id
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_user.userCode
     *
     * @return the value of itrip_user.userCode
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_user.userCode
     *
     * @param userCode the value for itrip_user.userCode
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_user.userPassword
     *
     * @return the value of itrip_user.userPassword
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_user.userPassword
     *
     * @param userPassword the value for itrip_user.userPassword
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_user.userType
     *
     * @return the value of itrip_user.userType
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_user.userType
     *
     * @param userType the value for itrip_user.userType
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_user.flatID
     *
     * @return the value of itrip_user.flatID
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Long getFlatID() {
        return flatID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_user.flatID
     *
     * @param flatID the value for itrip_user.flatID
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setFlatID(Long flatID) {
        this.flatID = flatID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_user.userName
     *
     * @return the value of itrip_user.userName
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_user.userName
     *
     * @param userName the value for itrip_user.userName
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_user.weChat
     *
     * @return the value of itrip_user.weChat
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public String getWeChat() {
        return weChat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_user.weChat
     *
     * @param weChat the value for itrip_user.weChat
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setWeChat(String weChat) {
        this.weChat = weChat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_user.QQ
     *
     * @return the value of itrip_user.QQ
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public String getQQ() {
        return QQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_user.QQ
     *
     * @param QQ the value for itrip_user.QQ
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setQQ(String QQ) {
        this.QQ = QQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_user.weibo
     *
     * @return the value of itrip_user.weibo
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public String getWeibo() {
        return weibo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_user.weibo
     *
     * @param weibo the value for itrip_user.weibo
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setWeibo(String weibo) {
        this.weibo = weibo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_user.baidu
     *
     * @return the value of itrip_user.baidu
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public String getBaidu() {
        return baidu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_user.baidu
     *
     * @param baidu the value for itrip_user.baidu
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setBaidu(String baidu) {
        this.baidu = baidu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_user.creationDate
     *
     * @return the value of itrip_user.creationDate
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_user.creationDate
     *
     * @param creationDate the value for itrip_user.creationDate
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_user.createdBy
     *
     * @return the value of itrip_user.createdBy
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_user.createdBy
     *
     * @param createdBy the value for itrip_user.createdBy
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_user.modifyDate
     *
     * @return the value of itrip_user.modifyDate
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_user.modifyDate
     *
     * @param modifyDate the value for itrip_user.modifyDate
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_user.modifiedBy
     *
     * @return the value of itrip_user.modifiedBy
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Long getModifiedBy() {
        return modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_user.modifiedBy
     *
     * @param modifiedBy the value for itrip_user.modifiedBy
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setModifiedBy(Long modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
}