package cn.itrip.beans.pojo;

import java.io.Serializable;

public class ItripOrderLinkUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_order_link_user.id
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_order_link_user.orderId
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_order_link_user.linkUserId
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Long linkUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table itrip_order_link_user
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_order_link_user.id
     *
     * @return the value of itrip_order_link_user.id
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_order_link_user.id
     *
     * @param id the value for itrip_order_link_user.id
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_order_link_user.orderId
     *
     * @return the value of itrip_order_link_user.orderId
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_order_link_user.orderId
     *
     * @param orderId the value for itrip_order_link_user.orderId
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_order_link_user.linkUserId
     *
     * @return the value of itrip_order_link_user.linkUserId
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Long getLinkUserId() {
        return linkUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_order_link_user.linkUserId
     *
     * @param linkUserId the value for itrip_order_link_user.linkUserId
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setLinkUserId(Long linkUserId) {
        this.linkUserId = linkUserId;
    }
}