package cn.itrip.beans.pojo;

import java.io.Serializable;
import java.util.Date;

public class ItripLabelDic implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_label_dic.id
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_label_dic.name
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_label_dic.value
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_label_dic.description
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_label_dic.parentId
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_label_dic.pic
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_label_dic.creationDate
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_label_dic.createdBy
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Long createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_label_dic.modifyDate
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_label_dic.modifiedBy
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Long modifiedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table itrip_label_dic
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_label_dic.id
     *
     * @return the value of itrip_label_dic.id
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_label_dic.id
     *
     * @param id the value for itrip_label_dic.id
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_label_dic.name
     *
     * @return the value of itrip_label_dic.name
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_label_dic.name
     *
     * @param name the value for itrip_label_dic.name
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_label_dic.value
     *
     * @return the value of itrip_label_dic.value
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_label_dic.value
     *
     * @param value the value for itrip_label_dic.value
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_label_dic.description
     *
     * @return the value of itrip_label_dic.description
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_label_dic.description
     *
     * @param description the value for itrip_label_dic.description
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_label_dic.parentId
     *
     * @return the value of itrip_label_dic.parentId
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_label_dic.parentId
     *
     * @param parentId the value for itrip_label_dic.parentId
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_label_dic.pic
     *
     * @return the value of itrip_label_dic.pic
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_label_dic.pic
     *
     * @param pic the value for itrip_label_dic.pic
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setPic(String pic) {
        this.pic = pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_label_dic.creationDate
     *
     * @return the value of itrip_label_dic.creationDate
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_label_dic.creationDate
     *
     * @param creationDate the value for itrip_label_dic.creationDate
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_label_dic.createdBy
     *
     * @return the value of itrip_label_dic.createdBy
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_label_dic.createdBy
     *
     * @param createdBy the value for itrip_label_dic.createdBy
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_label_dic.modifyDate
     *
     * @return the value of itrip_label_dic.modifyDate
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_label_dic.modifyDate
     *
     * @param modifyDate the value for itrip_label_dic.modifyDate
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_label_dic.modifiedBy
     *
     * @return the value of itrip_label_dic.modifiedBy
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Long getModifiedBy() {
        return modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_label_dic.modifiedBy
     *
     * @param modifiedBy the value for itrip_label_dic.modifiedBy
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setModifiedBy(Long modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
}