package cn.itrip.beans.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ItripCommentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table itrip_comment
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table itrip_comment
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table itrip_comment
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_comment
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public ItripCommentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_comment
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_comment
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_comment
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_comment
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_comment
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_comment
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_comment
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_comment
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_comment
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_comment
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table itrip_comment
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andHotelIdIsNull() {
            addCriterion("hotelId is null");
            return (Criteria) this;
        }

        public Criteria andHotelIdIsNotNull() {
            addCriterion("hotelId is not null");
            return (Criteria) this;
        }

        public Criteria andHotelIdEqualTo(Long value) {
            addCriterion("hotelId =", value, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdNotEqualTo(Long value) {
            addCriterion("hotelId <>", value, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdGreaterThan(Long value) {
            addCriterion("hotelId >", value, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdGreaterThanOrEqualTo(Long value) {
            addCriterion("hotelId >=", value, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdLessThan(Long value) {
            addCriterion("hotelId <", value, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdLessThanOrEqualTo(Long value) {
            addCriterion("hotelId <=", value, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdIn(List<Long> values) {
            addCriterion("hotelId in", values, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdNotIn(List<Long> values) {
            addCriterion("hotelId not in", values, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdBetween(Long value1, Long value2) {
            addCriterion("hotelId between", value1, value2, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdNotBetween(Long value1, Long value2) {
            addCriterion("hotelId not between", value1, value2, "hotelId");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNull() {
            addCriterion("productId is null");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNotNull() {
            addCriterion("productId is not null");
            return (Criteria) this;
        }

        public Criteria andProductIdEqualTo(Long value) {
            addCriterion("productId =", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotEqualTo(Long value) {
            addCriterion("productId <>", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThan(Long value) {
            addCriterion("productId >", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThanOrEqualTo(Long value) {
            addCriterion("productId >=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThan(Long value) {
            addCriterion("productId <", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThanOrEqualTo(Long value) {
            addCriterion("productId <=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdIn(List<Long> values) {
            addCriterion("productId in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotIn(List<Long> values) {
            addCriterion("productId not in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdBetween(Long value1, Long value2) {
            addCriterion("productId between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotBetween(Long value1, Long value2) {
            addCriterion("productId not between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductTypeIsNull() {
            addCriterion("productType is null");
            return (Criteria) this;
        }

        public Criteria andProductTypeIsNotNull() {
            addCriterion("productType is not null");
            return (Criteria) this;
        }

        public Criteria andProductTypeEqualTo(Integer value) {
            addCriterion("productType =", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeNotEqualTo(Integer value) {
            addCriterion("productType <>", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeGreaterThan(Integer value) {
            addCriterion("productType >", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("productType >=", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeLessThan(Integer value) {
            addCriterion("productType <", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeLessThanOrEqualTo(Integer value) {
            addCriterion("productType <=", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeIn(List<Integer> values) {
            addCriterion("productType in", values, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeNotIn(List<Integer> values) {
            addCriterion("productType not in", values, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeBetween(Integer value1, Integer value2) {
            addCriterion("productType between", value1, value2, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("productType not between", value1, value2, "productType");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("userId is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("userId is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("userId =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("userId <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("userId >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("userId >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("userId <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("userId <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("userId in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("userId not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("userId between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("userId not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andIsHavingImgIsNull() {
            addCriterion("isHavingImg is null");
            return (Criteria) this;
        }

        public Criteria andIsHavingImgIsNotNull() {
            addCriterion("isHavingImg is not null");
            return (Criteria) this;
        }

        public Criteria andIsHavingImgEqualTo(Integer value) {
            addCriterion("isHavingImg =", value, "isHavingImg");
            return (Criteria) this;
        }

        public Criteria andIsHavingImgNotEqualTo(Integer value) {
            addCriterion("isHavingImg <>", value, "isHavingImg");
            return (Criteria) this;
        }

        public Criteria andIsHavingImgGreaterThan(Integer value) {
            addCriterion("isHavingImg >", value, "isHavingImg");
            return (Criteria) this;
        }

        public Criteria andIsHavingImgGreaterThanOrEqualTo(Integer value) {
            addCriterion("isHavingImg >=", value, "isHavingImg");
            return (Criteria) this;
        }

        public Criteria andIsHavingImgLessThan(Integer value) {
            addCriterion("isHavingImg <", value, "isHavingImg");
            return (Criteria) this;
        }

        public Criteria andIsHavingImgLessThanOrEqualTo(Integer value) {
            addCriterion("isHavingImg <=", value, "isHavingImg");
            return (Criteria) this;
        }

        public Criteria andIsHavingImgIn(List<Integer> values) {
            addCriterion("isHavingImg in", values, "isHavingImg");
            return (Criteria) this;
        }

        public Criteria andIsHavingImgNotIn(List<Integer> values) {
            addCriterion("isHavingImg not in", values, "isHavingImg");
            return (Criteria) this;
        }

        public Criteria andIsHavingImgBetween(Integer value1, Integer value2) {
            addCriterion("isHavingImg between", value1, value2, "isHavingImg");
            return (Criteria) this;
        }

        public Criteria andIsHavingImgNotBetween(Integer value1, Integer value2) {
            addCriterion("isHavingImg not between", value1, value2, "isHavingImg");
            return (Criteria) this;
        }

        public Criteria andPositionScoreIsNull() {
            addCriterion("positionScore is null");
            return (Criteria) this;
        }

        public Criteria andPositionScoreIsNotNull() {
            addCriterion("positionScore is not null");
            return (Criteria) this;
        }

        public Criteria andPositionScoreEqualTo(Integer value) {
            addCriterion("positionScore =", value, "positionScore");
            return (Criteria) this;
        }

        public Criteria andPositionScoreNotEqualTo(Integer value) {
            addCriterion("positionScore <>", value, "positionScore");
            return (Criteria) this;
        }

        public Criteria andPositionScoreGreaterThan(Integer value) {
            addCriterion("positionScore >", value, "positionScore");
            return (Criteria) this;
        }

        public Criteria andPositionScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("positionScore >=", value, "positionScore");
            return (Criteria) this;
        }

        public Criteria andPositionScoreLessThan(Integer value) {
            addCriterion("positionScore <", value, "positionScore");
            return (Criteria) this;
        }

        public Criteria andPositionScoreLessThanOrEqualTo(Integer value) {
            addCriterion("positionScore <=", value, "positionScore");
            return (Criteria) this;
        }

        public Criteria andPositionScoreIn(List<Integer> values) {
            addCriterion("positionScore in", values, "positionScore");
            return (Criteria) this;
        }

        public Criteria andPositionScoreNotIn(List<Integer> values) {
            addCriterion("positionScore not in", values, "positionScore");
            return (Criteria) this;
        }

        public Criteria andPositionScoreBetween(Integer value1, Integer value2) {
            addCriterion("positionScore between", value1, value2, "positionScore");
            return (Criteria) this;
        }

        public Criteria andPositionScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("positionScore not between", value1, value2, "positionScore");
            return (Criteria) this;
        }

        public Criteria andFacilitiesScoreIsNull() {
            addCriterion("facilitiesScore is null");
            return (Criteria) this;
        }

        public Criteria andFacilitiesScoreIsNotNull() {
            addCriterion("facilitiesScore is not null");
            return (Criteria) this;
        }

        public Criteria andFacilitiesScoreEqualTo(Integer value) {
            addCriterion("facilitiesScore =", value, "facilitiesScore");
            return (Criteria) this;
        }

        public Criteria andFacilitiesScoreNotEqualTo(Integer value) {
            addCriterion("facilitiesScore <>", value, "facilitiesScore");
            return (Criteria) this;
        }

        public Criteria andFacilitiesScoreGreaterThan(Integer value) {
            addCriterion("facilitiesScore >", value, "facilitiesScore");
            return (Criteria) this;
        }

        public Criteria andFacilitiesScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("facilitiesScore >=", value, "facilitiesScore");
            return (Criteria) this;
        }

        public Criteria andFacilitiesScoreLessThan(Integer value) {
            addCriterion("facilitiesScore <", value, "facilitiesScore");
            return (Criteria) this;
        }

        public Criteria andFacilitiesScoreLessThanOrEqualTo(Integer value) {
            addCriterion("facilitiesScore <=", value, "facilitiesScore");
            return (Criteria) this;
        }

        public Criteria andFacilitiesScoreIn(List<Integer> values) {
            addCriterion("facilitiesScore in", values, "facilitiesScore");
            return (Criteria) this;
        }

        public Criteria andFacilitiesScoreNotIn(List<Integer> values) {
            addCriterion("facilitiesScore not in", values, "facilitiesScore");
            return (Criteria) this;
        }

        public Criteria andFacilitiesScoreBetween(Integer value1, Integer value2) {
            addCriterion("facilitiesScore between", value1, value2, "facilitiesScore");
            return (Criteria) this;
        }

        public Criteria andFacilitiesScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("facilitiesScore not between", value1, value2, "facilitiesScore");
            return (Criteria) this;
        }

        public Criteria andServiceScoreIsNull() {
            addCriterion("serviceScore is null");
            return (Criteria) this;
        }

        public Criteria andServiceScoreIsNotNull() {
            addCriterion("serviceScore is not null");
            return (Criteria) this;
        }

        public Criteria andServiceScoreEqualTo(Integer value) {
            addCriterion("serviceScore =", value, "serviceScore");
            return (Criteria) this;
        }

        public Criteria andServiceScoreNotEqualTo(Integer value) {
            addCriterion("serviceScore <>", value, "serviceScore");
            return (Criteria) this;
        }

        public Criteria andServiceScoreGreaterThan(Integer value) {
            addCriterion("serviceScore >", value, "serviceScore");
            return (Criteria) this;
        }

        public Criteria andServiceScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("serviceScore >=", value, "serviceScore");
            return (Criteria) this;
        }

        public Criteria andServiceScoreLessThan(Integer value) {
            addCriterion("serviceScore <", value, "serviceScore");
            return (Criteria) this;
        }

        public Criteria andServiceScoreLessThanOrEqualTo(Integer value) {
            addCriterion("serviceScore <=", value, "serviceScore");
            return (Criteria) this;
        }

        public Criteria andServiceScoreIn(List<Integer> values) {
            addCriterion("serviceScore in", values, "serviceScore");
            return (Criteria) this;
        }

        public Criteria andServiceScoreNotIn(List<Integer> values) {
            addCriterion("serviceScore not in", values, "serviceScore");
            return (Criteria) this;
        }

        public Criteria andServiceScoreBetween(Integer value1, Integer value2) {
            addCriterion("serviceScore between", value1, value2, "serviceScore");
            return (Criteria) this;
        }

        public Criteria andServiceScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("serviceScore not between", value1, value2, "serviceScore");
            return (Criteria) this;
        }

        public Criteria andHygieneScoreIsNull() {
            addCriterion("hygieneScore is null");
            return (Criteria) this;
        }

        public Criteria andHygieneScoreIsNotNull() {
            addCriterion("hygieneScore is not null");
            return (Criteria) this;
        }

        public Criteria andHygieneScoreEqualTo(Integer value) {
            addCriterion("hygieneScore =", value, "hygieneScore");
            return (Criteria) this;
        }

        public Criteria andHygieneScoreNotEqualTo(Integer value) {
            addCriterion("hygieneScore <>", value, "hygieneScore");
            return (Criteria) this;
        }

        public Criteria andHygieneScoreGreaterThan(Integer value) {
            addCriterion("hygieneScore >", value, "hygieneScore");
            return (Criteria) this;
        }

        public Criteria andHygieneScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("hygieneScore >=", value, "hygieneScore");
            return (Criteria) this;
        }

        public Criteria andHygieneScoreLessThan(Integer value) {
            addCriterion("hygieneScore <", value, "hygieneScore");
            return (Criteria) this;
        }

        public Criteria andHygieneScoreLessThanOrEqualTo(Integer value) {
            addCriterion("hygieneScore <=", value, "hygieneScore");
            return (Criteria) this;
        }

        public Criteria andHygieneScoreIn(List<Integer> values) {
            addCriterion("hygieneScore in", values, "hygieneScore");
            return (Criteria) this;
        }

        public Criteria andHygieneScoreNotIn(List<Integer> values) {
            addCriterion("hygieneScore not in", values, "hygieneScore");
            return (Criteria) this;
        }

        public Criteria andHygieneScoreBetween(Integer value1, Integer value2) {
            addCriterion("hygieneScore between", value1, value2, "hygieneScore");
            return (Criteria) this;
        }

        public Criteria andHygieneScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("hygieneScore not between", value1, value2, "hygieneScore");
            return (Criteria) this;
        }

        public Criteria andScoreIsNull() {
            addCriterion("score is null");
            return (Criteria) this;
        }

        public Criteria andScoreIsNotNull() {
            addCriterion("score is not null");
            return (Criteria) this;
        }

        public Criteria andScoreEqualTo(Integer value) {
            addCriterion("score =", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotEqualTo(Integer value) {
            addCriterion("score <>", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThan(Integer value) {
            addCriterion("score >", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("score >=", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLessThan(Integer value) {
            addCriterion("score <", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLessThanOrEqualTo(Integer value) {
            addCriterion("score <=", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreIn(List<Integer> values) {
            addCriterion("score in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotIn(List<Integer> values) {
            addCriterion("score not in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreBetween(Integer value1, Integer value2) {
            addCriterion("score between", value1, value2, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("score not between", value1, value2, "score");
            return (Criteria) this;
        }

        public Criteria andTripModeIsNull() {
            addCriterion("tripMode is null");
            return (Criteria) this;
        }

        public Criteria andTripModeIsNotNull() {
            addCriterion("tripMode is not null");
            return (Criteria) this;
        }

        public Criteria andTripModeEqualTo(String value) {
            addCriterion("tripMode =", value, "tripMode");
            return (Criteria) this;
        }

        public Criteria andTripModeNotEqualTo(String value) {
            addCriterion("tripMode <>", value, "tripMode");
            return (Criteria) this;
        }

        public Criteria andTripModeGreaterThan(String value) {
            addCriterion("tripMode >", value, "tripMode");
            return (Criteria) this;
        }

        public Criteria andTripModeGreaterThanOrEqualTo(String value) {
            addCriterion("tripMode >=", value, "tripMode");
            return (Criteria) this;
        }

        public Criteria andTripModeLessThan(String value) {
            addCriterion("tripMode <", value, "tripMode");
            return (Criteria) this;
        }

        public Criteria andTripModeLessThanOrEqualTo(String value) {
            addCriterion("tripMode <=", value, "tripMode");
            return (Criteria) this;
        }

        public Criteria andTripModeLike(String value) {
            addCriterion("tripMode like", value, "tripMode");
            return (Criteria) this;
        }

        public Criteria andTripModeNotLike(String value) {
            addCriterion("tripMode not like", value, "tripMode");
            return (Criteria) this;
        }

        public Criteria andTripModeIn(List<String> values) {
            addCriterion("tripMode in", values, "tripMode");
            return (Criteria) this;
        }

        public Criteria andTripModeNotIn(List<String> values) {
            addCriterion("tripMode not in", values, "tripMode");
            return (Criteria) this;
        }

        public Criteria andTripModeBetween(String value1, String value2) {
            addCriterion("tripMode between", value1, value2, "tripMode");
            return (Criteria) this;
        }

        public Criteria andTripModeNotBetween(String value1, String value2) {
            addCriterion("tripMode not between", value1, value2, "tripMode");
            return (Criteria) this;
        }

        public Criteria andIsOkIsNull() {
            addCriterion("isOk is null");
            return (Criteria) this;
        }

        public Criteria andIsOkIsNotNull() {
            addCriterion("isOk is not null");
            return (Criteria) this;
        }

        public Criteria andIsOkEqualTo(Integer value) {
            addCriterion("isOk =", value, "isOk");
            return (Criteria) this;
        }

        public Criteria andIsOkNotEqualTo(Integer value) {
            addCriterion("isOk <>", value, "isOk");
            return (Criteria) this;
        }

        public Criteria andIsOkGreaterThan(Integer value) {
            addCriterion("isOk >", value, "isOk");
            return (Criteria) this;
        }

        public Criteria andIsOkGreaterThanOrEqualTo(Integer value) {
            addCriterion("isOk >=", value, "isOk");
            return (Criteria) this;
        }

        public Criteria andIsOkLessThan(Integer value) {
            addCriterion("isOk <", value, "isOk");
            return (Criteria) this;
        }

        public Criteria andIsOkLessThanOrEqualTo(Integer value) {
            addCriterion("isOk <=", value, "isOk");
            return (Criteria) this;
        }

        public Criteria andIsOkIn(List<Integer> values) {
            addCriterion("isOk in", values, "isOk");
            return (Criteria) this;
        }

        public Criteria andIsOkNotIn(List<Integer> values) {
            addCriterion("isOk not in", values, "isOk");
            return (Criteria) this;
        }

        public Criteria andIsOkBetween(Integer value1, Integer value2) {
            addCriterion("isOk between", value1, value2, "isOk");
            return (Criteria) this;
        }

        public Criteria andIsOkNotBetween(Integer value1, Integer value2) {
            addCriterion("isOk not between", value1, value2, "isOk");
            return (Criteria) this;
        }

        public Criteria andCreationDateIsNull() {
            addCriterion("creationDate is null");
            return (Criteria) this;
        }

        public Criteria andCreationDateIsNotNull() {
            addCriterion("creationDate is not null");
            return (Criteria) this;
        }

        public Criteria andCreationDateEqualTo(Date value) {
            addCriterion("creationDate =", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateNotEqualTo(Date value) {
            addCriterion("creationDate <>", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateGreaterThan(Date value) {
            addCriterion("creationDate >", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateGreaterThanOrEqualTo(Date value) {
            addCriterion("creationDate >=", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateLessThan(Date value) {
            addCriterion("creationDate <", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateLessThanOrEqualTo(Date value) {
            addCriterion("creationDate <=", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateIn(List<Date> values) {
            addCriterion("creationDate in", values, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateNotIn(List<Date> values) {
            addCriterion("creationDate not in", values, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateBetween(Date value1, Date value2) {
            addCriterion("creationDate between", value1, value2, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateNotBetween(Date value1, Date value2) {
            addCriterion("creationDate not between", value1, value2, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("createdBy is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("createdBy is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(Long value) {
            addCriterion("createdBy =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(Long value) {
            addCriterion("createdBy <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(Long value) {
            addCriterion("createdBy >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(Long value) {
            addCriterion("createdBy >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(Long value) {
            addCriterion("createdBy <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(Long value) {
            addCriterion("createdBy <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<Long> values) {
            addCriterion("createdBy in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<Long> values) {
            addCriterion("createdBy not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(Long value1, Long value2) {
            addCriterion("createdBy between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(Long value1, Long value2) {
            addCriterion("createdBy not between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andModifyDateIsNull() {
            addCriterion("modifyDate is null");
            return (Criteria) this;
        }

        public Criteria andModifyDateIsNotNull() {
            addCriterion("modifyDate is not null");
            return (Criteria) this;
        }

        public Criteria andModifyDateEqualTo(Date value) {
            addCriterion("modifyDate =", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotEqualTo(Date value) {
            addCriterion("modifyDate <>", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateGreaterThan(Date value) {
            addCriterion("modifyDate >", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateGreaterThanOrEqualTo(Date value) {
            addCriterion("modifyDate >=", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateLessThan(Date value) {
            addCriterion("modifyDate <", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateLessThanOrEqualTo(Date value) {
            addCriterion("modifyDate <=", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateIn(List<Date> values) {
            addCriterion("modifyDate in", values, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotIn(List<Date> values) {
            addCriterion("modifyDate not in", values, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateBetween(Date value1, Date value2) {
            addCriterion("modifyDate between", value1, value2, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotBetween(Date value1, Date value2) {
            addCriterion("modifyDate not between", value1, value2, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifiedByIsNull() {
            addCriterion("modifiedBy is null");
            return (Criteria) this;
        }

        public Criteria andModifiedByIsNotNull() {
            addCriterion("modifiedBy is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedByEqualTo(Long value) {
            addCriterion("modifiedBy =", value, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andModifiedByNotEqualTo(Long value) {
            addCriterion("modifiedBy <>", value, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andModifiedByGreaterThan(Long value) {
            addCriterion("modifiedBy >", value, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andModifiedByGreaterThanOrEqualTo(Long value) {
            addCriterion("modifiedBy >=", value, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andModifiedByLessThan(Long value) {
            addCriterion("modifiedBy <", value, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andModifiedByLessThanOrEqualTo(Long value) {
            addCriterion("modifiedBy <=", value, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andModifiedByIn(List<Long> values) {
            addCriterion("modifiedBy in", values, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andModifiedByNotIn(List<Long> values) {
            addCriterion("modifiedBy not in", values, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andModifiedByBetween(Long value1, Long value2) {
            addCriterion("modifiedBy between", value1, value2, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andModifiedByNotBetween(Long value1, Long value2) {
            addCriterion("modifiedBy not between", value1, value2, "modifiedBy");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table itrip_comment
     *
     * @mbggenerated do_not_delete_during_merge Tue Apr 25 11:19:39 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table itrip_comment
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}