package cn.itrip.beans.pojo;

import java.io.Serializable;
import java.util.Date;

public class ItripUserLinkUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_user_link_User.id
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_user_link_User.linkUserName
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private String linkUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_user_link_User.linkIdCard
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private String linkIdCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_user_link_User.linkPhone
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private String linkPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_user_link_User.userId
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_user_link_User.creationDate
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_user_link_User.createdBy
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Long createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_user_link_User.modifyDate
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_user_link_User.modifiedBy
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Long modifiedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table itrip_user_link_User
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_user_link_User.id
     *
     * @return the value of itrip_user_link_User.id
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_user_link_User.id
     *
     * @param id the value for itrip_user_link_User.id
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_user_link_User.linkUserName
     *
     * @return the value of itrip_user_link_User.linkUserName
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public String getLinkUserName() {
        return linkUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_user_link_User.linkUserName
     *
     * @param linkUserName the value for itrip_user_link_User.linkUserName
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setLinkUserName(String linkUserName) {
        this.linkUserName = linkUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_user_link_User.linkIdCard
     *
     * @return the value of itrip_user_link_User.linkIdCard
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public String getLinkIdCard() {
        return linkIdCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_user_link_User.linkIdCard
     *
     * @param linkIdCard the value for itrip_user_link_User.linkIdCard
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setLinkIdCard(String linkIdCard) {
        this.linkIdCard = linkIdCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_user_link_User.linkPhone
     *
     * @return the value of itrip_user_link_User.linkPhone
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public String getLinkPhone() {
        return linkPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_user_link_User.linkPhone
     *
     * @param linkPhone the value for itrip_user_link_User.linkPhone
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setLinkPhone(String linkPhone) {
        this.linkPhone = linkPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_user_link_User.userId
     *
     * @return the value of itrip_user_link_User.userId
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_user_link_User.userId
     *
     * @param userId the value for itrip_user_link_User.userId
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_user_link_User.creationDate
     *
     * @return the value of itrip_user_link_User.creationDate
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_user_link_User.creationDate
     *
     * @param creationDate the value for itrip_user_link_User.creationDate
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_user_link_User.createdBy
     *
     * @return the value of itrip_user_link_User.createdBy
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_user_link_User.createdBy
     *
     * @param createdBy the value for itrip_user_link_User.createdBy
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_user_link_User.modifyDate
     *
     * @return the value of itrip_user_link_User.modifyDate
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_user_link_User.modifyDate
     *
     * @param modifyDate the value for itrip_user_link_User.modifyDate
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_user_link_User.modifiedBy
     *
     * @return the value of itrip_user_link_User.modifiedBy
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Long getModifiedBy() {
        return modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_user_link_User.modifiedBy
     *
     * @param modifiedBy the value for itrip_user_link_User.modifiedBy
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setModifiedBy(Long modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
}