package cn.itrip.beans.pojo;

import java.io.Serializable;
import java.util.Date;

public class ItripHotelRoom implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_room.id
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_room.hotelId
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Long hotelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_room.roomTitle
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private String roomTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_room.roomPrice
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Long roomPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_room.roomBedTypeId
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Long roomBedTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_room.isHavingBreakfast
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Integer isHavingBreakfast;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_room.payType
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Integer payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_room.satisfaction
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Double satisfaction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_room.isBook
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Integer isBook;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_room.isCancel
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Integer isCancel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_room.isTimelyResponse
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Integer isTimelyResponse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_room.creationDate
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_room.createdBy
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Long createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_room.modifyDate
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_room.modifiedBy
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Long modifiedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table itrip_hotel_room
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_room.id
     *
     * @return the value of itrip_hotel_room.id
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_room.id
     *
     * @param id the value for itrip_hotel_room.id
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_room.hotelId
     *
     * @return the value of itrip_hotel_room.hotelId
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Long getHotelId() {
        return hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_room.hotelId
     *
     * @param hotelId the value for itrip_hotel_room.hotelId
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setHotelId(Long hotelId) {
        this.hotelId = hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_room.roomTitle
     *
     * @return the value of itrip_hotel_room.roomTitle
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public String getRoomTitle() {
        return roomTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_room.roomTitle
     *
     * @param roomTitle the value for itrip_hotel_room.roomTitle
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setRoomTitle(String roomTitle) {
        this.roomTitle = roomTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_room.roomPrice
     *
     * @return the value of itrip_hotel_room.roomPrice
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Long getRoomPrice() {
        return roomPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_room.roomPrice
     *
     * @param roomPrice the value for itrip_hotel_room.roomPrice
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setRoomPrice(Long roomPrice) {
        this.roomPrice = roomPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_room.roomBedTypeId
     *
     * @return the value of itrip_hotel_room.roomBedTypeId
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Long getRoomBedTypeId() {
        return roomBedTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_room.roomBedTypeId
     *
     * @param roomBedTypeId the value for itrip_hotel_room.roomBedTypeId
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setRoomBedTypeId(Long roomBedTypeId) {
        this.roomBedTypeId = roomBedTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_room.isHavingBreakfast
     *
     * @return the value of itrip_hotel_room.isHavingBreakfast
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Integer getIsHavingBreakfast() {
        return isHavingBreakfast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_room.isHavingBreakfast
     *
     * @param isHavingBreakfast the value for itrip_hotel_room.isHavingBreakfast
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setIsHavingBreakfast(Integer isHavingBreakfast) {
        this.isHavingBreakfast = isHavingBreakfast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_room.payType
     *
     * @return the value of itrip_hotel_room.payType
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Integer getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_room.payType
     *
     * @param payType the value for itrip_hotel_room.payType
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_room.satisfaction
     *
     * @return the value of itrip_hotel_room.satisfaction
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Double getSatisfaction() {
        return satisfaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_room.satisfaction
     *
     * @param satisfaction the value for itrip_hotel_room.satisfaction
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setSatisfaction(Double satisfaction) {
        this.satisfaction = satisfaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_room.isBook
     *
     * @return the value of itrip_hotel_room.isBook
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Integer getIsBook() {
        return isBook;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_room.isBook
     *
     * @param isBook the value for itrip_hotel_room.isBook
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setIsBook(Integer isBook) {
        this.isBook = isBook;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_room.isCancel
     *
     * @return the value of itrip_hotel_room.isCancel
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Integer getIsCancel() {
        return isCancel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_room.isCancel
     *
     * @param isCancel the value for itrip_hotel_room.isCancel
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setIsCancel(Integer isCancel) {
        this.isCancel = isCancel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_room.isTimelyResponse
     *
     * @return the value of itrip_hotel_room.isTimelyResponse
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Integer getIsTimelyResponse() {
        return isTimelyResponse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_room.isTimelyResponse
     *
     * @param isTimelyResponse the value for itrip_hotel_room.isTimelyResponse
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setIsTimelyResponse(Integer isTimelyResponse) {
        this.isTimelyResponse = isTimelyResponse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_room.creationDate
     *
     * @return the value of itrip_hotel_room.creationDate
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_room.creationDate
     *
     * @param creationDate the value for itrip_hotel_room.creationDate
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_room.createdBy
     *
     * @return the value of itrip_hotel_room.createdBy
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_room.createdBy
     *
     * @param createdBy the value for itrip_hotel_room.createdBy
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_room.modifyDate
     *
     * @return the value of itrip_hotel_room.modifyDate
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_room.modifyDate
     *
     * @param modifyDate the value for itrip_hotel_room.modifyDate
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_room.modifiedBy
     *
     * @return the value of itrip_hotel_room.modifiedBy
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Long getModifiedBy() {
        return modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_room.modifiedBy
     *
     * @param modifiedBy the value for itrip_hotel_room.modifiedBy
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setModifiedBy(Long modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
}