package cn.itrip.beans.pojo;

import java.io.Serializable;

public class ItripHotelExtendProperty implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_extend_property.id
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_extend_property.hotelId
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Long hotelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_extend_property.extendPropertyId
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Long extendPropertyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table itrip_hotel_extend_property
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_extend_property.id
     *
     * @return the value of itrip_hotel_extend_property.id
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_extend_property.id
     *
     * @param id the value for itrip_hotel_extend_property.id
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_extend_property.hotelId
     *
     * @return the value of itrip_hotel_extend_property.hotelId
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Long getHotelId() {
        return hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_extend_property.hotelId
     *
     * @param hotelId the value for itrip_hotel_extend_property.hotelId
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setHotelId(Long hotelId) {
        this.hotelId = hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_extend_property.extendPropertyId
     *
     * @return the value of itrip_hotel_extend_property.extendPropertyId
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Long getExtendPropertyId() {
        return extendPropertyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_extend_property.extendPropertyId
     *
     * @param extendPropertyId the value for itrip_hotel_extend_property.extendPropertyId
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setExtendPropertyId(Long extendPropertyId) {
        this.extendPropertyId = extendPropertyId;
    }
}