package cn.itrip.beans.pojo;

import java.io.Serializable;
import java.util.Date;

public class ItripHotel implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel.id
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel.hotelName
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private String hotelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel.countryId
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Long countryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel.countryName
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private String countryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel.provinceId
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Long provinceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel.provinceName
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private String provinceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel.cityId
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Long cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel.cityName
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel.address
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel.details
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private String details;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel.facilities
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private String facilities;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel.hotelPolicy
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private String hotelPolicy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel.hotelType
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Integer hotelType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel.hotelLevel
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Integer hotelLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel.isGroupPurchase
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Integer isGroupPurchase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel.minPrice
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Long minPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel.maxPrice
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Long maxPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel.hotelStore
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Integer hotelStore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel.creationDate
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel.createdBy
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Long createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel.modifyDate
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel.modifiedBy
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private Long modifiedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table itrip_hotel
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel.id
     *
     * @return the value of itrip_hotel.id
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel.id
     *
     * @param id the value for itrip_hotel.id
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel.hotelName
     *
     * @return the value of itrip_hotel.hotelName
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public String getHotelName() {
        return hotelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel.hotelName
     *
     * @param hotelName the value for itrip_hotel.hotelName
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setHotelName(String hotelName) {
        this.hotelName = hotelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel.countryId
     *
     * @return the value of itrip_hotel.countryId
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Long getCountryId() {
        return countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel.countryId
     *
     * @param countryId the value for itrip_hotel.countryId
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setCountryId(Long countryId) {
        this.countryId = countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel.countryName
     *
     * @return the value of itrip_hotel.countryName
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public String getCountryName() {
        return countryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel.countryName
     *
     * @param countryName the value for itrip_hotel.countryName
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setCountryName(String countryName) {
        this.countryName = countryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel.provinceId
     *
     * @return the value of itrip_hotel.provinceId
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Long getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel.provinceId
     *
     * @param provinceId the value for itrip_hotel.provinceId
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setProvinceId(Long provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel.provinceName
     *
     * @return the value of itrip_hotel.provinceName
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel.provinceName
     *
     * @param provinceName the value for itrip_hotel.provinceName
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel.cityId
     *
     * @return the value of itrip_hotel.cityId
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Long getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel.cityId
     *
     * @param cityId the value for itrip_hotel.cityId
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setCityId(Long cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel.cityName
     *
     * @return the value of itrip_hotel.cityName
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel.cityName
     *
     * @param cityName the value for itrip_hotel.cityName
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel.address
     *
     * @return the value of itrip_hotel.address
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel.address
     *
     * @param address the value for itrip_hotel.address
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel.details
     *
     * @return the value of itrip_hotel.details
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public String getDetails() {
        return details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel.details
     *
     * @param details the value for itrip_hotel.details
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setDetails(String details) {
        this.details = details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel.facilities
     *
     * @return the value of itrip_hotel.facilities
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public String getFacilities() {
        return facilities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel.facilities
     *
     * @param facilities the value for itrip_hotel.facilities
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setFacilities(String facilities) {
        this.facilities = facilities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel.hotelPolicy
     *
     * @return the value of itrip_hotel.hotelPolicy
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public String getHotelPolicy() {
        return hotelPolicy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel.hotelPolicy
     *
     * @param hotelPolicy the value for itrip_hotel.hotelPolicy
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setHotelPolicy(String hotelPolicy) {
        this.hotelPolicy = hotelPolicy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel.hotelType
     *
     * @return the value of itrip_hotel.hotelType
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Integer getHotelType() {
        return hotelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel.hotelType
     *
     * @param hotelType the value for itrip_hotel.hotelType
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setHotelType(Integer hotelType) {
        this.hotelType = hotelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel.hotelLevel
     *
     * @return the value of itrip_hotel.hotelLevel
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Integer getHotelLevel() {
        return hotelLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel.hotelLevel
     *
     * @param hotelLevel the value for itrip_hotel.hotelLevel
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setHotelLevel(Integer hotelLevel) {
        this.hotelLevel = hotelLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel.isGroupPurchase
     *
     * @return the value of itrip_hotel.isGroupPurchase
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Integer getIsGroupPurchase() {
        return isGroupPurchase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel.isGroupPurchase
     *
     * @param isGroupPurchase the value for itrip_hotel.isGroupPurchase
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setIsGroupPurchase(Integer isGroupPurchase) {
        this.isGroupPurchase = isGroupPurchase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel.minPrice
     *
     * @return the value of itrip_hotel.minPrice
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Long getMinPrice() {
        return minPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel.minPrice
     *
     * @param minPrice the value for itrip_hotel.minPrice
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setMinPrice(Long minPrice) {
        this.minPrice = minPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel.maxPrice
     *
     * @return the value of itrip_hotel.maxPrice
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Long getMaxPrice() {
        return maxPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel.maxPrice
     *
     * @param maxPrice the value for itrip_hotel.maxPrice
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setMaxPrice(Long maxPrice) {
        this.maxPrice = maxPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel.hotelStore
     *
     * @return the value of itrip_hotel.hotelStore
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Integer getHotelStore() {
        return hotelStore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel.hotelStore
     *
     * @param hotelStore the value for itrip_hotel.hotelStore
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setHotelStore(Integer hotelStore) {
        this.hotelStore = hotelStore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel.creationDate
     *
     * @return the value of itrip_hotel.creationDate
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel.creationDate
     *
     * @param creationDate the value for itrip_hotel.creationDate
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel.createdBy
     *
     * @return the value of itrip_hotel.createdBy
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel.createdBy
     *
     * @param createdBy the value for itrip_hotel.createdBy
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel.modifyDate
     *
     * @return the value of itrip_hotel.modifyDate
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel.modifyDate
     *
     * @param modifyDate the value for itrip_hotel.modifyDate
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel.modifiedBy
     *
     * @return the value of itrip_hotel.modifiedBy
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Long getModifiedBy() {
        return modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel.modifiedBy
     *
     * @param modifiedBy the value for itrip_hotel.modifiedBy
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setModifiedBy(Long modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
}