package cn.itrip.beans.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ItripHotelOrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table itrip_hotel_order
     *
     * @mbggenerated Wed May 03 09:27:28 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table itrip_hotel_order
     *
     * @mbggenerated Wed May 03 09:27:28 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table itrip_hotel_order
     *
     * @mbggenerated Wed May 03 09:27:28 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_order
     *
     * @mbggenerated Wed May 03 09:27:28 CST 2017
     */
    public ItripHotelOrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_order
     *
     * @mbggenerated Wed May 03 09:27:28 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_order
     *
     * @mbggenerated Wed May 03 09:27:28 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_order
     *
     * @mbggenerated Wed May 03 09:27:28 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_order
     *
     * @mbggenerated Wed May 03 09:27:28 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_order
     *
     * @mbggenerated Wed May 03 09:27:28 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_order
     *
     * @mbggenerated Wed May 03 09:27:28 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_order
     *
     * @mbggenerated Wed May 03 09:27:28 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_order
     *
     * @mbggenerated Wed May 03 09:27:28 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_order
     *
     * @mbggenerated Wed May 03 09:27:28 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_order
     *
     * @mbggenerated Wed May 03 09:27:28 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table itrip_hotel_order
     *
     * @mbggenerated Wed May 03 09:27:28 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("userId is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("userId is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("userId =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("userId <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("userId >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("userId >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("userId <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("userId <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("userId in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("userId not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("userId between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("userId not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNull() {
            addCriterion("orderNo is null");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNotNull() {
            addCriterion("orderNo is not null");
            return (Criteria) this;
        }

        public Criteria andOrderNoEqualTo(Integer value) {
            addCriterion("orderNo =", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotEqualTo(Integer value) {
            addCriterion("orderNo <>", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoGreaterThan(Integer value) {
            addCriterion("orderNo >", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("orderNo >=", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLessThan(Integer value) {
            addCriterion("orderNo <", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLessThanOrEqualTo(Integer value) {
            addCriterion("orderNo <=", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoIn(List<Integer> values) {
            addCriterion("orderNo in", values, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotIn(List<Integer> values) {
            addCriterion("orderNo not in", values, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoBetween(Integer value1, Integer value2) {
            addCriterion("orderNo between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotBetween(Integer value1, Integer value2) {
            addCriterion("orderNo not between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andHotelIdIsNull() {
            addCriterion("hotelId is null");
            return (Criteria) this;
        }

        public Criteria andHotelIdIsNotNull() {
            addCriterion("hotelId is not null");
            return (Criteria) this;
        }

        public Criteria andHotelIdEqualTo(Long value) {
            addCriterion("hotelId =", value, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdNotEqualTo(Long value) {
            addCriterion("hotelId <>", value, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdGreaterThan(Long value) {
            addCriterion("hotelId >", value, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdGreaterThanOrEqualTo(Long value) {
            addCriterion("hotelId >=", value, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdLessThan(Long value) {
            addCriterion("hotelId <", value, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdLessThanOrEqualTo(Long value) {
            addCriterion("hotelId <=", value, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdIn(List<Long> values) {
            addCriterion("hotelId in", values, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdNotIn(List<Long> values) {
            addCriterion("hotelId not in", values, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdBetween(Long value1, Long value2) {
            addCriterion("hotelId between", value1, value2, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdNotBetween(Long value1, Long value2) {
            addCriterion("hotelId not between", value1, value2, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelNameIsNull() {
            addCriterion("hotelName is null");
            return (Criteria) this;
        }

        public Criteria andHotelNameIsNotNull() {
            addCriterion("hotelName is not null");
            return (Criteria) this;
        }

        public Criteria andHotelNameEqualTo(String value) {
            addCriterion("hotelName =", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameNotEqualTo(String value) {
            addCriterion("hotelName <>", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameGreaterThan(String value) {
            addCriterion("hotelName >", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameGreaterThanOrEqualTo(String value) {
            addCriterion("hotelName >=", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameLessThan(String value) {
            addCriterion("hotelName <", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameLessThanOrEqualTo(String value) {
            addCriterion("hotelName <=", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameLike(String value) {
            addCriterion("hotelName like", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameNotLike(String value) {
            addCriterion("hotelName not like", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameIn(List<String> values) {
            addCriterion("hotelName in", values, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameNotIn(List<String> values) {
            addCriterion("hotelName not in", values, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameBetween(String value1, String value2) {
            addCriterion("hotelName between", value1, value2, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameNotBetween(String value1, String value2) {
            addCriterion("hotelName not between", value1, value2, "hotelName");
            return (Criteria) this;
        }

        public Criteria andRoomIdIsNull() {
            addCriterion("roomId is null");
            return (Criteria) this;
        }

        public Criteria andRoomIdIsNotNull() {
            addCriterion("roomId is not null");
            return (Criteria) this;
        }

        public Criteria andRoomIdEqualTo(Long value) {
            addCriterion("roomId =", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdNotEqualTo(Long value) {
            addCriterion("roomId <>", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdGreaterThan(Long value) {
            addCriterion("roomId >", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdGreaterThanOrEqualTo(Long value) {
            addCriterion("roomId >=", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdLessThan(Long value) {
            addCriterion("roomId <", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdLessThanOrEqualTo(Long value) {
            addCriterion("roomId <=", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdIn(List<Long> values) {
            addCriterion("roomId in", values, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdNotIn(List<Long> values) {
            addCriterion("roomId not in", values, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdBetween(Long value1, Long value2) {
            addCriterion("roomId between", value1, value2, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdNotBetween(Long value1, Long value2) {
            addCriterion("roomId not between", value1, value2, "roomId");
            return (Criteria) this;
        }

        public Criteria andCountIsNull() {
            addCriterion("count is null");
            return (Criteria) this;
        }

        public Criteria andCountIsNotNull() {
            addCriterion("count is not null");
            return (Criteria) this;
        }

        public Criteria andCountEqualTo(Integer value) {
            addCriterion("count =", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotEqualTo(Integer value) {
            addCriterion("count <>", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountGreaterThan(Integer value) {
            addCriterion("count >", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("count >=", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountLessThan(Integer value) {
            addCriterion("count <", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountLessThanOrEqualTo(Integer value) {
            addCriterion("count <=", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountIn(List<Integer> values) {
            addCriterion("count in", values, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotIn(List<Integer> values) {
            addCriterion("count not in", values, "count");
            return (Criteria) this;
        }

        public Criteria andCountBetween(Integer value1, Integer value2) {
            addCriterion("count between", value1, value2, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotBetween(Integer value1, Integer value2) {
            addCriterion("count not between", value1, value2, "count");
            return (Criteria) this;
        }

        public Criteria andBookingDaysIsNull() {
            addCriterion("bookingDays is null");
            return (Criteria) this;
        }

        public Criteria andBookingDaysIsNotNull() {
            addCriterion("bookingDays is not null");
            return (Criteria) this;
        }

        public Criteria andBookingDaysEqualTo(Integer value) {
            addCriterion("bookingDays =", value, "bookingDays");
            return (Criteria) this;
        }

        public Criteria andBookingDaysNotEqualTo(Integer value) {
            addCriterion("bookingDays <>", value, "bookingDays");
            return (Criteria) this;
        }

        public Criteria andBookingDaysGreaterThan(Integer value) {
            addCriterion("bookingDays >", value, "bookingDays");
            return (Criteria) this;
        }

        public Criteria andBookingDaysGreaterThanOrEqualTo(Integer value) {
            addCriterion("bookingDays >=", value, "bookingDays");
            return (Criteria) this;
        }

        public Criteria andBookingDaysLessThan(Integer value) {
            addCriterion("bookingDays <", value, "bookingDays");
            return (Criteria) this;
        }

        public Criteria andBookingDaysLessThanOrEqualTo(Integer value) {
            addCriterion("bookingDays <=", value, "bookingDays");
            return (Criteria) this;
        }

        public Criteria andBookingDaysIn(List<Integer> values) {
            addCriterion("bookingDays in", values, "bookingDays");
            return (Criteria) this;
        }

        public Criteria andBookingDaysNotIn(List<Integer> values) {
            addCriterion("bookingDays not in", values, "bookingDays");
            return (Criteria) this;
        }

        public Criteria andBookingDaysBetween(Integer value1, Integer value2) {
            addCriterion("bookingDays between", value1, value2, "bookingDays");
            return (Criteria) this;
        }

        public Criteria andBookingDaysNotBetween(Integer value1, Integer value2) {
            addCriterion("bookingDays not between", value1, value2, "bookingDays");
            return (Criteria) this;
        }

        public Criteria andCheckInDateIsNull() {
            addCriterion("checkInDate is null");
            return (Criteria) this;
        }

        public Criteria andCheckInDateIsNotNull() {
            addCriterion("checkInDate is not null");
            return (Criteria) this;
        }

        public Criteria andCheckInDateEqualTo(Date value) {
            addCriterion("checkInDate =", value, "checkInDate");
            return (Criteria) this;
        }

        public Criteria andCheckInDateNotEqualTo(Date value) {
            addCriterion("checkInDate <>", value, "checkInDate");
            return (Criteria) this;
        }

        public Criteria andCheckInDateGreaterThan(Date value) {
            addCriterion("checkInDate >", value, "checkInDate");
            return (Criteria) this;
        }

        public Criteria andCheckInDateGreaterThanOrEqualTo(Date value) {
            addCriterion("checkInDate >=", value, "checkInDate");
            return (Criteria) this;
        }

        public Criteria andCheckInDateLessThan(Date value) {
            addCriterion("checkInDate <", value, "checkInDate");
            return (Criteria) this;
        }

        public Criteria andCheckInDateLessThanOrEqualTo(Date value) {
            addCriterion("checkInDate <=", value, "checkInDate");
            return (Criteria) this;
        }

        public Criteria andCheckInDateIn(List<Date> values) {
            addCriterion("checkInDate in", values, "checkInDate");
            return (Criteria) this;
        }

        public Criteria andCheckInDateNotIn(List<Date> values) {
            addCriterion("checkInDate not in", values, "checkInDate");
            return (Criteria) this;
        }

        public Criteria andCheckInDateBetween(Date value1, Date value2) {
            addCriterion("checkInDate between", value1, value2, "checkInDate");
            return (Criteria) this;
        }

        public Criteria andCheckInDateNotBetween(Date value1, Date value2) {
            addCriterion("checkInDate not between", value1, value2, "checkInDate");
            return (Criteria) this;
        }

        public Criteria andCheckOutDateIsNull() {
            addCriterion("checkOutDate is null");
            return (Criteria) this;
        }

        public Criteria andCheckOutDateIsNotNull() {
            addCriterion("checkOutDate is not null");
            return (Criteria) this;
        }

        public Criteria andCheckOutDateEqualTo(Date value) {
            addCriterion("checkOutDate =", value, "checkOutDate");
            return (Criteria) this;
        }

        public Criteria andCheckOutDateNotEqualTo(Date value) {
            addCriterion("checkOutDate <>", value, "checkOutDate");
            return (Criteria) this;
        }

        public Criteria andCheckOutDateGreaterThan(Date value) {
            addCriterion("checkOutDate >", value, "checkOutDate");
            return (Criteria) this;
        }

        public Criteria andCheckOutDateGreaterThanOrEqualTo(Date value) {
            addCriterion("checkOutDate >=", value, "checkOutDate");
            return (Criteria) this;
        }

        public Criteria andCheckOutDateLessThan(Date value) {
            addCriterion("checkOutDate <", value, "checkOutDate");
            return (Criteria) this;
        }

        public Criteria andCheckOutDateLessThanOrEqualTo(Date value) {
            addCriterion("checkOutDate <=", value, "checkOutDate");
            return (Criteria) this;
        }

        public Criteria andCheckOutDateIn(List<Date> values) {
            addCriterion("checkOutDate in", values, "checkOutDate");
            return (Criteria) this;
        }

        public Criteria andCheckOutDateNotIn(List<Date> values) {
            addCriterion("checkOutDate not in", values, "checkOutDate");
            return (Criteria) this;
        }

        public Criteria andCheckOutDateBetween(Date value1, Date value2) {
            addCriterion("checkOutDate between", value1, value2, "checkOutDate");
            return (Criteria) this;
        }

        public Criteria andCheckOutDateNotBetween(Date value1, Date value2) {
            addCriterion("checkOutDate not between", value1, value2, "checkOutDate");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIsNull() {
            addCriterion("orderStatus is null");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIsNotNull() {
            addCriterion("orderStatus is not null");
            return (Criteria) this;
        }

        public Criteria andOrderStatusEqualTo(Integer value) {
            addCriterion("orderStatus =", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusNotEqualTo(Integer value) {
            addCriterion("orderStatus <>", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusGreaterThan(Integer value) {
            addCriterion("orderStatus >", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("orderStatus >=", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusLessThan(Integer value) {
            addCriterion("orderStatus <", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusLessThanOrEqualTo(Integer value) {
            addCriterion("orderStatus <=", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIn(List<Integer> values) {
            addCriterion("orderStatus in", values, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusNotIn(List<Integer> values) {
            addCriterion("orderStatus not in", values, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusBetween(Integer value1, Integer value2) {
            addCriterion("orderStatus between", value1, value2, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("orderStatus not between", value1, value2, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andPayAmountIsNull() {
            addCriterion("payAmount is null");
            return (Criteria) this;
        }

        public Criteria andPayAmountIsNotNull() {
            addCriterion("payAmount is not null");
            return (Criteria) this;
        }

        public Criteria andPayAmountEqualTo(Long value) {
            addCriterion("payAmount =", value, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountNotEqualTo(Long value) {
            addCriterion("payAmount <>", value, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountGreaterThan(Long value) {
            addCriterion("payAmount >", value, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("payAmount >=", value, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountLessThan(Long value) {
            addCriterion("payAmount <", value, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountLessThanOrEqualTo(Long value) {
            addCriterion("payAmount <=", value, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountIn(List<Long> values) {
            addCriterion("payAmount in", values, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountNotIn(List<Long> values) {
            addCriterion("payAmount not in", values, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountBetween(Long value1, Long value2) {
            addCriterion("payAmount between", value1, value2, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountNotBetween(Long value1, Long value2) {
            addCriterion("payAmount not between", value1, value2, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayTypeIsNull() {
            addCriterion("payType is null");
            return (Criteria) this;
        }

        public Criteria andPayTypeIsNotNull() {
            addCriterion("payType is not null");
            return (Criteria) this;
        }

        public Criteria andPayTypeEqualTo(Integer value) {
            addCriterion("payType =", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeNotEqualTo(Integer value) {
            addCriterion("payType <>", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeGreaterThan(Integer value) {
            addCriterion("payType >", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("payType >=", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeLessThan(Integer value) {
            addCriterion("payType <", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeLessThanOrEqualTo(Integer value) {
            addCriterion("payType <=", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeIn(List<Integer> values) {
            addCriterion("payType in", values, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeNotIn(List<Integer> values) {
            addCriterion("payType not in", values, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeBetween(Integer value1, Integer value2) {
            addCriterion("payType between", value1, value2, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("payType not between", value1, value2, "payType");
            return (Criteria) this;
        }

        public Criteria andNoticePhoneIsNull() {
            addCriterion("noticePhone is null");
            return (Criteria) this;
        }

        public Criteria andNoticePhoneIsNotNull() {
            addCriterion("noticePhone is not null");
            return (Criteria) this;
        }

        public Criteria andNoticePhoneEqualTo(String value) {
            addCriterion("noticePhone =", value, "noticePhone");
            return (Criteria) this;
        }

        public Criteria andNoticePhoneNotEqualTo(String value) {
            addCriterion("noticePhone <>", value, "noticePhone");
            return (Criteria) this;
        }

        public Criteria andNoticePhoneGreaterThan(String value) {
            addCriterion("noticePhone >", value, "noticePhone");
            return (Criteria) this;
        }

        public Criteria andNoticePhoneGreaterThanOrEqualTo(String value) {
            addCriterion("noticePhone >=", value, "noticePhone");
            return (Criteria) this;
        }

        public Criteria andNoticePhoneLessThan(String value) {
            addCriterion("noticePhone <", value, "noticePhone");
            return (Criteria) this;
        }

        public Criteria andNoticePhoneLessThanOrEqualTo(String value) {
            addCriterion("noticePhone <=", value, "noticePhone");
            return (Criteria) this;
        }

        public Criteria andNoticePhoneLike(String value) {
            addCriterion("noticePhone like", value, "noticePhone");
            return (Criteria) this;
        }

        public Criteria andNoticePhoneNotLike(String value) {
            addCriterion("noticePhone not like", value, "noticePhone");
            return (Criteria) this;
        }

        public Criteria andNoticePhoneIn(List<String> values) {
            addCriterion("noticePhone in", values, "noticePhone");
            return (Criteria) this;
        }

        public Criteria andNoticePhoneNotIn(List<String> values) {
            addCriterion("noticePhone not in", values, "noticePhone");
            return (Criteria) this;
        }

        public Criteria andNoticePhoneBetween(String value1, String value2) {
            addCriterion("noticePhone between", value1, value2, "noticePhone");
            return (Criteria) this;
        }

        public Criteria andNoticePhoneNotBetween(String value1, String value2) {
            addCriterion("noticePhone not between", value1, value2, "noticePhone");
            return (Criteria) this;
        }

        public Criteria andNoticeEmailIsNull() {
            addCriterion("noticeEmail is null");
            return (Criteria) this;
        }

        public Criteria andNoticeEmailIsNotNull() {
            addCriterion("noticeEmail is not null");
            return (Criteria) this;
        }

        public Criteria andNoticeEmailEqualTo(String value) {
            addCriterion("noticeEmail =", value, "noticeEmail");
            return (Criteria) this;
        }

        public Criteria andNoticeEmailNotEqualTo(String value) {
            addCriterion("noticeEmail <>", value, "noticeEmail");
            return (Criteria) this;
        }

        public Criteria andNoticeEmailGreaterThan(String value) {
            addCriterion("noticeEmail >", value, "noticeEmail");
            return (Criteria) this;
        }

        public Criteria andNoticeEmailGreaterThanOrEqualTo(String value) {
            addCriterion("noticeEmail >=", value, "noticeEmail");
            return (Criteria) this;
        }

        public Criteria andNoticeEmailLessThan(String value) {
            addCriterion("noticeEmail <", value, "noticeEmail");
            return (Criteria) this;
        }

        public Criteria andNoticeEmailLessThanOrEqualTo(String value) {
            addCriterion("noticeEmail <=", value, "noticeEmail");
            return (Criteria) this;
        }

        public Criteria andNoticeEmailLike(String value) {
            addCriterion("noticeEmail like", value, "noticeEmail");
            return (Criteria) this;
        }

        public Criteria andNoticeEmailNotLike(String value) {
            addCriterion("noticeEmail not like", value, "noticeEmail");
            return (Criteria) this;
        }

        public Criteria andNoticeEmailIn(List<String> values) {
            addCriterion("noticeEmail in", values, "noticeEmail");
            return (Criteria) this;
        }

        public Criteria andNoticeEmailNotIn(List<String> values) {
            addCriterion("noticeEmail not in", values, "noticeEmail");
            return (Criteria) this;
        }

        public Criteria andNoticeEmailBetween(String value1, String value2) {
            addCriterion("noticeEmail between", value1, value2, "noticeEmail");
            return (Criteria) this;
        }

        public Criteria andNoticeEmailNotBetween(String value1, String value2) {
            addCriterion("noticeEmail not between", value1, value2, "noticeEmail");
            return (Criteria) this;
        }

        public Criteria andIsNeedInvoiceIsNull() {
            addCriterion("isNeedInvoice is null");
            return (Criteria) this;
        }

        public Criteria andIsNeedInvoiceIsNotNull() {
            addCriterion("isNeedInvoice is not null");
            return (Criteria) this;
        }

        public Criteria andIsNeedInvoiceEqualTo(Integer value) {
            addCriterion("isNeedInvoice =", value, "isNeedInvoice");
            return (Criteria) this;
        }

        public Criteria andIsNeedInvoiceNotEqualTo(Integer value) {
            addCriterion("isNeedInvoice <>", value, "isNeedInvoice");
            return (Criteria) this;
        }

        public Criteria andIsNeedInvoiceGreaterThan(Integer value) {
            addCriterion("isNeedInvoice >", value, "isNeedInvoice");
            return (Criteria) this;
        }

        public Criteria andIsNeedInvoiceGreaterThanOrEqualTo(Integer value) {
            addCriterion("isNeedInvoice >=", value, "isNeedInvoice");
            return (Criteria) this;
        }

        public Criteria andIsNeedInvoiceLessThan(Integer value) {
            addCriterion("isNeedInvoice <", value, "isNeedInvoice");
            return (Criteria) this;
        }

        public Criteria andIsNeedInvoiceLessThanOrEqualTo(Integer value) {
            addCriterion("isNeedInvoice <=", value, "isNeedInvoice");
            return (Criteria) this;
        }

        public Criteria andIsNeedInvoiceIn(List<Integer> values) {
            addCriterion("isNeedInvoice in", values, "isNeedInvoice");
            return (Criteria) this;
        }

        public Criteria andIsNeedInvoiceNotIn(List<Integer> values) {
            addCriterion("isNeedInvoice not in", values, "isNeedInvoice");
            return (Criteria) this;
        }

        public Criteria andIsNeedInvoiceBetween(Integer value1, Integer value2) {
            addCriterion("isNeedInvoice between", value1, value2, "isNeedInvoice");
            return (Criteria) this;
        }

        public Criteria andIsNeedInvoiceNotBetween(Integer value1, Integer value2) {
            addCriterion("isNeedInvoice not between", value1, value2, "isNeedInvoice");
            return (Criteria) this;
        }

        public Criteria andInvoiceTypeIsNull() {
            addCriterion("invoiceType is null");
            return (Criteria) this;
        }

        public Criteria andInvoiceTypeIsNotNull() {
            addCriterion("invoiceType is not null");
            return (Criteria) this;
        }

        public Criteria andInvoiceTypeEqualTo(Integer value) {
            addCriterion("invoiceType =", value, "invoiceType");
            return (Criteria) this;
        }

        public Criteria andInvoiceTypeNotEqualTo(Integer value) {
            addCriterion("invoiceType <>", value, "invoiceType");
            return (Criteria) this;
        }

        public Criteria andInvoiceTypeGreaterThan(Integer value) {
            addCriterion("invoiceType >", value, "invoiceType");
            return (Criteria) this;
        }

        public Criteria andInvoiceTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("invoiceType >=", value, "invoiceType");
            return (Criteria) this;
        }

        public Criteria andInvoiceTypeLessThan(Integer value) {
            addCriterion("invoiceType <", value, "invoiceType");
            return (Criteria) this;
        }

        public Criteria andInvoiceTypeLessThanOrEqualTo(Integer value) {
            addCriterion("invoiceType <=", value, "invoiceType");
            return (Criteria) this;
        }

        public Criteria andInvoiceTypeIn(List<Integer> values) {
            addCriterion("invoiceType in", values, "invoiceType");
            return (Criteria) this;
        }

        public Criteria andInvoiceTypeNotIn(List<Integer> values) {
            addCriterion("invoiceType not in", values, "invoiceType");
            return (Criteria) this;
        }

        public Criteria andInvoiceTypeBetween(Integer value1, Integer value2) {
            addCriterion("invoiceType between", value1, value2, "invoiceType");
            return (Criteria) this;
        }

        public Criteria andInvoiceTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("invoiceType not between", value1, value2, "invoiceType");
            return (Criteria) this;
        }

        public Criteria andInvoiceHeadIsNull() {
            addCriterion("invoiceHead is null");
            return (Criteria) this;
        }

        public Criteria andInvoiceHeadIsNotNull() {
            addCriterion("invoiceHead is not null");
            return (Criteria) this;
        }

        public Criteria andInvoiceHeadEqualTo(String value) {
            addCriterion("invoiceHead =", value, "invoiceHead");
            return (Criteria) this;
        }

        public Criteria andInvoiceHeadNotEqualTo(String value) {
            addCriterion("invoiceHead <>", value, "invoiceHead");
            return (Criteria) this;
        }

        public Criteria andInvoiceHeadGreaterThan(String value) {
            addCriterion("invoiceHead >", value, "invoiceHead");
            return (Criteria) this;
        }

        public Criteria andInvoiceHeadGreaterThanOrEqualTo(String value) {
            addCriterion("invoiceHead >=", value, "invoiceHead");
            return (Criteria) this;
        }

        public Criteria andInvoiceHeadLessThan(String value) {
            addCriterion("invoiceHead <", value, "invoiceHead");
            return (Criteria) this;
        }

        public Criteria andInvoiceHeadLessThanOrEqualTo(String value) {
            addCriterion("invoiceHead <=", value, "invoiceHead");
            return (Criteria) this;
        }

        public Criteria andInvoiceHeadLike(String value) {
            addCriterion("invoiceHead like", value, "invoiceHead");
            return (Criteria) this;
        }

        public Criteria andInvoiceHeadNotLike(String value) {
            addCriterion("invoiceHead not like", value, "invoiceHead");
            return (Criteria) this;
        }

        public Criteria andInvoiceHeadIn(List<String> values) {
            addCriterion("invoiceHead in", values, "invoiceHead");
            return (Criteria) this;
        }

        public Criteria andInvoiceHeadNotIn(List<String> values) {
            addCriterion("invoiceHead not in", values, "invoiceHead");
            return (Criteria) this;
        }

        public Criteria andInvoiceHeadBetween(String value1, String value2) {
            addCriterion("invoiceHead between", value1, value2, "invoiceHead");
            return (Criteria) this;
        }

        public Criteria andInvoiceHeadNotBetween(String value1, String value2) {
            addCriterion("invoiceHead not between", value1, value2, "invoiceHead");
            return (Criteria) this;
        }

        public Criteria andCreationDateIsNull() {
            addCriterion("creationDate is null");
            return (Criteria) this;
        }

        public Criteria andCreationDateIsNotNull() {
            addCriterion("creationDate is not null");
            return (Criteria) this;
        }

        public Criteria andCreationDateEqualTo(Date value) {
            addCriterion("creationDate =", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateNotEqualTo(Date value) {
            addCriterion("creationDate <>", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateGreaterThan(Date value) {
            addCriterion("creationDate >", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateGreaterThanOrEqualTo(Date value) {
            addCriterion("creationDate >=", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateLessThan(Date value) {
            addCriterion("creationDate <", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateLessThanOrEqualTo(Date value) {
            addCriterion("creationDate <=", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateIn(List<Date> values) {
            addCriterion("creationDate in", values, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateNotIn(List<Date> values) {
            addCriterion("creationDate not in", values, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateBetween(Date value1, Date value2) {
            addCriterion("creationDate between", value1, value2, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateNotBetween(Date value1, Date value2) {
            addCriterion("creationDate not between", value1, value2, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("createdBy is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("createdBy is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(Long value) {
            addCriterion("createdBy =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(Long value) {
            addCriterion("createdBy <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(Long value) {
            addCriterion("createdBy >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(Long value) {
            addCriterion("createdBy >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(Long value) {
            addCriterion("createdBy <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(Long value) {
            addCriterion("createdBy <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<Long> values) {
            addCriterion("createdBy in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<Long> values) {
            addCriterion("createdBy not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(Long value1, Long value2) {
            addCriterion("createdBy between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(Long value1, Long value2) {
            addCriterion("createdBy not between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andModifyDateIsNull() {
            addCriterion("modifyDate is null");
            return (Criteria) this;
        }

        public Criteria andModifyDateIsNotNull() {
            addCriterion("modifyDate is not null");
            return (Criteria) this;
        }

        public Criteria andModifyDateEqualTo(Date value) {
            addCriterion("modifyDate =", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotEqualTo(Date value) {
            addCriterion("modifyDate <>", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateGreaterThan(Date value) {
            addCriterion("modifyDate >", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateGreaterThanOrEqualTo(Date value) {
            addCriterion("modifyDate >=", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateLessThan(Date value) {
            addCriterion("modifyDate <", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateLessThanOrEqualTo(Date value) {
            addCriterion("modifyDate <=", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateIn(List<Date> values) {
            addCriterion("modifyDate in", values, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotIn(List<Date> values) {
            addCriterion("modifyDate not in", values, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateBetween(Date value1, Date value2) {
            addCriterion("modifyDate between", value1, value2, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotBetween(Date value1, Date value2) {
            addCriterion("modifyDate not between", value1, value2, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifiedByIsNull() {
            addCriterion("modifiedBy is null");
            return (Criteria) this;
        }

        public Criteria andModifiedByIsNotNull() {
            addCriterion("modifiedBy is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedByEqualTo(Long value) {
            addCriterion("modifiedBy =", value, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andModifiedByNotEqualTo(Long value) {
            addCriterion("modifiedBy <>", value, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andModifiedByGreaterThan(Long value) {
            addCriterion("modifiedBy >", value, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andModifiedByGreaterThanOrEqualTo(Long value) {
            addCriterion("modifiedBy >=", value, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andModifiedByLessThan(Long value) {
            addCriterion("modifiedBy <", value, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andModifiedByLessThanOrEqualTo(Long value) {
            addCriterion("modifiedBy <=", value, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andModifiedByIn(List<Long> values) {
            addCriterion("modifiedBy in", values, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andModifiedByNotIn(List<Long> values) {
            addCriterion("modifiedBy not in", values, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andModifiedByBetween(Long value1, Long value2) {
            addCriterion("modifiedBy between", value1, value2, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andModifiedByNotBetween(Long value1, Long value2) {
            addCriterion("modifiedBy not between", value1, value2, "modifiedBy");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table itrip_hotel_order
     *
     * @mbggenerated do_not_delete_during_merge Wed May 03 09:27:28 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table itrip_hotel_order
     *
     * @mbggenerated Wed May 03 09:27:28 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}