package cn.itrip.beans.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ItripHotelExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table itrip_hotel
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table itrip_hotel
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table itrip_hotel
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public ItripHotelExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table itrip_hotel
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andHotelNameIsNull() {
            addCriterion("hotelName is null");
            return (Criteria) this;
        }

        public Criteria andHotelNameIsNotNull() {
            addCriterion("hotelName is not null");
            return (Criteria) this;
        }

        public Criteria andHotelNameEqualTo(String value) {
            addCriterion("hotelName =", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameNotEqualTo(String value) {
            addCriterion("hotelName <>", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameGreaterThan(String value) {
            addCriterion("hotelName >", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameGreaterThanOrEqualTo(String value) {
            addCriterion("hotelName >=", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameLessThan(String value) {
            addCriterion("hotelName <", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameLessThanOrEqualTo(String value) {
            addCriterion("hotelName <=", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameLike(String value) {
            addCriterion("hotelName like", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameNotLike(String value) {
            addCriterion("hotelName not like", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameIn(List<String> values) {
            addCriterion("hotelName in", values, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameNotIn(List<String> values) {
            addCriterion("hotelName not in", values, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameBetween(String value1, String value2) {
            addCriterion("hotelName between", value1, value2, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameNotBetween(String value1, String value2) {
            addCriterion("hotelName not between", value1, value2, "hotelName");
            return (Criteria) this;
        }

        public Criteria andCountryIdIsNull() {
            addCriterion("countryId is null");
            return (Criteria) this;
        }

        public Criteria andCountryIdIsNotNull() {
            addCriterion("countryId is not null");
            return (Criteria) this;
        }

        public Criteria andCountryIdEqualTo(Long value) {
            addCriterion("countryId =", value, "countryId");
            return (Criteria) this;
        }

        public Criteria andCountryIdNotEqualTo(Long value) {
            addCriterion("countryId <>", value, "countryId");
            return (Criteria) this;
        }

        public Criteria andCountryIdGreaterThan(Long value) {
            addCriterion("countryId >", value, "countryId");
            return (Criteria) this;
        }

        public Criteria andCountryIdGreaterThanOrEqualTo(Long value) {
            addCriterion("countryId >=", value, "countryId");
            return (Criteria) this;
        }

        public Criteria andCountryIdLessThan(Long value) {
            addCriterion("countryId <", value, "countryId");
            return (Criteria) this;
        }

        public Criteria andCountryIdLessThanOrEqualTo(Long value) {
            addCriterion("countryId <=", value, "countryId");
            return (Criteria) this;
        }

        public Criteria andCountryIdIn(List<Long> values) {
            addCriterion("countryId in", values, "countryId");
            return (Criteria) this;
        }

        public Criteria andCountryIdNotIn(List<Long> values) {
            addCriterion("countryId not in", values, "countryId");
            return (Criteria) this;
        }

        public Criteria andCountryIdBetween(Long value1, Long value2) {
            addCriterion("countryId between", value1, value2, "countryId");
            return (Criteria) this;
        }

        public Criteria andCountryIdNotBetween(Long value1, Long value2) {
            addCriterion("countryId not between", value1, value2, "countryId");
            return (Criteria) this;
        }

        public Criteria andCountryNameIsNull() {
            addCriterion("countryName is null");
            return (Criteria) this;
        }

        public Criteria andCountryNameIsNotNull() {
            addCriterion("countryName is not null");
            return (Criteria) this;
        }

        public Criteria andCountryNameEqualTo(String value) {
            addCriterion("countryName =", value, "countryName");
            return (Criteria) this;
        }

        public Criteria andCountryNameNotEqualTo(String value) {
            addCriterion("countryName <>", value, "countryName");
            return (Criteria) this;
        }

        public Criteria andCountryNameGreaterThan(String value) {
            addCriterion("countryName >", value, "countryName");
            return (Criteria) this;
        }

        public Criteria andCountryNameGreaterThanOrEqualTo(String value) {
            addCriterion("countryName >=", value, "countryName");
            return (Criteria) this;
        }

        public Criteria andCountryNameLessThan(String value) {
            addCriterion("countryName <", value, "countryName");
            return (Criteria) this;
        }

        public Criteria andCountryNameLessThanOrEqualTo(String value) {
            addCriterion("countryName <=", value, "countryName");
            return (Criteria) this;
        }

        public Criteria andCountryNameLike(String value) {
            addCriterion("countryName like", value, "countryName");
            return (Criteria) this;
        }

        public Criteria andCountryNameNotLike(String value) {
            addCriterion("countryName not like", value, "countryName");
            return (Criteria) this;
        }

        public Criteria andCountryNameIn(List<String> values) {
            addCriterion("countryName in", values, "countryName");
            return (Criteria) this;
        }

        public Criteria andCountryNameNotIn(List<String> values) {
            addCriterion("countryName not in", values, "countryName");
            return (Criteria) this;
        }

        public Criteria andCountryNameBetween(String value1, String value2) {
            addCriterion("countryName between", value1, value2, "countryName");
            return (Criteria) this;
        }

        public Criteria andCountryNameNotBetween(String value1, String value2) {
            addCriterion("countryName not between", value1, value2, "countryName");
            return (Criteria) this;
        }

        public Criteria andProvinceIdIsNull() {
            addCriterion("provinceId is null");
            return (Criteria) this;
        }

        public Criteria andProvinceIdIsNotNull() {
            addCriterion("provinceId is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceIdEqualTo(Long value) {
            addCriterion("provinceId =", value, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdNotEqualTo(Long value) {
            addCriterion("provinceId <>", value, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdGreaterThan(Long value) {
            addCriterion("provinceId >", value, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdGreaterThanOrEqualTo(Long value) {
            addCriterion("provinceId >=", value, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdLessThan(Long value) {
            addCriterion("provinceId <", value, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdLessThanOrEqualTo(Long value) {
            addCriterion("provinceId <=", value, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdIn(List<Long> values) {
            addCriterion("provinceId in", values, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdNotIn(List<Long> values) {
            addCriterion("provinceId not in", values, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdBetween(Long value1, Long value2) {
            addCriterion("provinceId between", value1, value2, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdNotBetween(Long value1, Long value2) {
            addCriterion("provinceId not between", value1, value2, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceNameIsNull() {
            addCriterion("provinceName is null");
            return (Criteria) this;
        }

        public Criteria andProvinceNameIsNotNull() {
            addCriterion("provinceName is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceNameEqualTo(String value) {
            addCriterion("provinceName =", value, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameNotEqualTo(String value) {
            addCriterion("provinceName <>", value, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameGreaterThan(String value) {
            addCriterion("provinceName >", value, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameGreaterThanOrEqualTo(String value) {
            addCriterion("provinceName >=", value, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameLessThan(String value) {
            addCriterion("provinceName <", value, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameLessThanOrEqualTo(String value) {
            addCriterion("provinceName <=", value, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameLike(String value) {
            addCriterion("provinceName like", value, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameNotLike(String value) {
            addCriterion("provinceName not like", value, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameIn(List<String> values) {
            addCriterion("provinceName in", values, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameNotIn(List<String> values) {
            addCriterion("provinceName not in", values, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameBetween(String value1, String value2) {
            addCriterion("provinceName between", value1, value2, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameNotBetween(String value1, String value2) {
            addCriterion("provinceName not between", value1, value2, "provinceName");
            return (Criteria) this;
        }

        public Criteria andCityIdIsNull() {
            addCriterion("cityId is null");
            return (Criteria) this;
        }

        public Criteria andCityIdIsNotNull() {
            addCriterion("cityId is not null");
            return (Criteria) this;
        }

        public Criteria andCityIdEqualTo(Long value) {
            addCriterion("cityId =", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotEqualTo(Long value) {
            addCriterion("cityId <>", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdGreaterThan(Long value) {
            addCriterion("cityId >", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdGreaterThanOrEqualTo(Long value) {
            addCriterion("cityId >=", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdLessThan(Long value) {
            addCriterion("cityId <", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdLessThanOrEqualTo(Long value) {
            addCriterion("cityId <=", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdIn(List<Long> values) {
            addCriterion("cityId in", values, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotIn(List<Long> values) {
            addCriterion("cityId not in", values, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdBetween(Long value1, Long value2) {
            addCriterion("cityId between", value1, value2, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotBetween(Long value1, Long value2) {
            addCriterion("cityId not between", value1, value2, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityNameIsNull() {
            addCriterion("cityName is null");
            return (Criteria) this;
        }

        public Criteria andCityNameIsNotNull() {
            addCriterion("cityName is not null");
            return (Criteria) this;
        }

        public Criteria andCityNameEqualTo(String value) {
            addCriterion("cityName =", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameNotEqualTo(String value) {
            addCriterion("cityName <>", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameGreaterThan(String value) {
            addCriterion("cityName >", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameGreaterThanOrEqualTo(String value) {
            addCriterion("cityName >=", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameLessThan(String value) {
            addCriterion("cityName <", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameLessThanOrEqualTo(String value) {
            addCriterion("cityName <=", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameLike(String value) {
            addCriterion("cityName like", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameNotLike(String value) {
            addCriterion("cityName not like", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameIn(List<String> values) {
            addCriterion("cityName in", values, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameNotIn(List<String> values) {
            addCriterion("cityName not in", values, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameBetween(String value1, String value2) {
            addCriterion("cityName between", value1, value2, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameNotBetween(String value1, String value2) {
            addCriterion("cityName not between", value1, value2, "cityName");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andDetailsIsNull() {
            addCriterion("details is null");
            return (Criteria) this;
        }

        public Criteria andDetailsIsNotNull() {
            addCriterion("details is not null");
            return (Criteria) this;
        }

        public Criteria andDetailsEqualTo(String value) {
            addCriterion("details =", value, "details");
            return (Criteria) this;
        }

        public Criteria andDetailsNotEqualTo(String value) {
            addCriterion("details <>", value, "details");
            return (Criteria) this;
        }

        public Criteria andDetailsGreaterThan(String value) {
            addCriterion("details >", value, "details");
            return (Criteria) this;
        }

        public Criteria andDetailsGreaterThanOrEqualTo(String value) {
            addCriterion("details >=", value, "details");
            return (Criteria) this;
        }

        public Criteria andDetailsLessThan(String value) {
            addCriterion("details <", value, "details");
            return (Criteria) this;
        }

        public Criteria andDetailsLessThanOrEqualTo(String value) {
            addCriterion("details <=", value, "details");
            return (Criteria) this;
        }

        public Criteria andDetailsLike(String value) {
            addCriterion("details like", value, "details");
            return (Criteria) this;
        }

        public Criteria andDetailsNotLike(String value) {
            addCriterion("details not like", value, "details");
            return (Criteria) this;
        }

        public Criteria andDetailsIn(List<String> values) {
            addCriterion("details in", values, "details");
            return (Criteria) this;
        }

        public Criteria andDetailsNotIn(List<String> values) {
            addCriterion("details not in", values, "details");
            return (Criteria) this;
        }

        public Criteria andDetailsBetween(String value1, String value2) {
            addCriterion("details between", value1, value2, "details");
            return (Criteria) this;
        }

        public Criteria andDetailsNotBetween(String value1, String value2) {
            addCriterion("details not between", value1, value2, "details");
            return (Criteria) this;
        }

        public Criteria andFacilitiesIsNull() {
            addCriterion("facilities is null");
            return (Criteria) this;
        }

        public Criteria andFacilitiesIsNotNull() {
            addCriterion("facilities is not null");
            return (Criteria) this;
        }

        public Criteria andFacilitiesEqualTo(String value) {
            addCriterion("facilities =", value, "facilities");
            return (Criteria) this;
        }

        public Criteria andFacilitiesNotEqualTo(String value) {
            addCriterion("facilities <>", value, "facilities");
            return (Criteria) this;
        }

        public Criteria andFacilitiesGreaterThan(String value) {
            addCriterion("facilities >", value, "facilities");
            return (Criteria) this;
        }

        public Criteria andFacilitiesGreaterThanOrEqualTo(String value) {
            addCriterion("facilities >=", value, "facilities");
            return (Criteria) this;
        }

        public Criteria andFacilitiesLessThan(String value) {
            addCriterion("facilities <", value, "facilities");
            return (Criteria) this;
        }

        public Criteria andFacilitiesLessThanOrEqualTo(String value) {
            addCriterion("facilities <=", value, "facilities");
            return (Criteria) this;
        }

        public Criteria andFacilitiesLike(String value) {
            addCriterion("facilities like", value, "facilities");
            return (Criteria) this;
        }

        public Criteria andFacilitiesNotLike(String value) {
            addCriterion("facilities not like", value, "facilities");
            return (Criteria) this;
        }

        public Criteria andFacilitiesIn(List<String> values) {
            addCriterion("facilities in", values, "facilities");
            return (Criteria) this;
        }

        public Criteria andFacilitiesNotIn(List<String> values) {
            addCriterion("facilities not in", values, "facilities");
            return (Criteria) this;
        }

        public Criteria andFacilitiesBetween(String value1, String value2) {
            addCriterion("facilities between", value1, value2, "facilities");
            return (Criteria) this;
        }

        public Criteria andFacilitiesNotBetween(String value1, String value2) {
            addCriterion("facilities not between", value1, value2, "facilities");
            return (Criteria) this;
        }

        public Criteria andHotelPolicyIsNull() {
            addCriterion("hotelPolicy is null");
            return (Criteria) this;
        }

        public Criteria andHotelPolicyIsNotNull() {
            addCriterion("hotelPolicy is not null");
            return (Criteria) this;
        }

        public Criteria andHotelPolicyEqualTo(String value) {
            addCriterion("hotelPolicy =", value, "hotelPolicy");
            return (Criteria) this;
        }

        public Criteria andHotelPolicyNotEqualTo(String value) {
            addCriterion("hotelPolicy <>", value, "hotelPolicy");
            return (Criteria) this;
        }

        public Criteria andHotelPolicyGreaterThan(String value) {
            addCriterion("hotelPolicy >", value, "hotelPolicy");
            return (Criteria) this;
        }

        public Criteria andHotelPolicyGreaterThanOrEqualTo(String value) {
            addCriterion("hotelPolicy >=", value, "hotelPolicy");
            return (Criteria) this;
        }

        public Criteria andHotelPolicyLessThan(String value) {
            addCriterion("hotelPolicy <", value, "hotelPolicy");
            return (Criteria) this;
        }

        public Criteria andHotelPolicyLessThanOrEqualTo(String value) {
            addCriterion("hotelPolicy <=", value, "hotelPolicy");
            return (Criteria) this;
        }

        public Criteria andHotelPolicyLike(String value) {
            addCriterion("hotelPolicy like", value, "hotelPolicy");
            return (Criteria) this;
        }

        public Criteria andHotelPolicyNotLike(String value) {
            addCriterion("hotelPolicy not like", value, "hotelPolicy");
            return (Criteria) this;
        }

        public Criteria andHotelPolicyIn(List<String> values) {
            addCriterion("hotelPolicy in", values, "hotelPolicy");
            return (Criteria) this;
        }

        public Criteria andHotelPolicyNotIn(List<String> values) {
            addCriterion("hotelPolicy not in", values, "hotelPolicy");
            return (Criteria) this;
        }

        public Criteria andHotelPolicyBetween(String value1, String value2) {
            addCriterion("hotelPolicy between", value1, value2, "hotelPolicy");
            return (Criteria) this;
        }

        public Criteria andHotelPolicyNotBetween(String value1, String value2) {
            addCriterion("hotelPolicy not between", value1, value2, "hotelPolicy");
            return (Criteria) this;
        }

        public Criteria andHotelTypeIsNull() {
            addCriterion("hotelType is null");
            return (Criteria) this;
        }

        public Criteria andHotelTypeIsNotNull() {
            addCriterion("hotelType is not null");
            return (Criteria) this;
        }

        public Criteria andHotelTypeEqualTo(Integer value) {
            addCriterion("hotelType =", value, "hotelType");
            return (Criteria) this;
        }

        public Criteria andHotelTypeNotEqualTo(Integer value) {
            addCriterion("hotelType <>", value, "hotelType");
            return (Criteria) this;
        }

        public Criteria andHotelTypeGreaterThan(Integer value) {
            addCriterion("hotelType >", value, "hotelType");
            return (Criteria) this;
        }

        public Criteria andHotelTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("hotelType >=", value, "hotelType");
            return (Criteria) this;
        }

        public Criteria andHotelTypeLessThan(Integer value) {
            addCriterion("hotelType <", value, "hotelType");
            return (Criteria) this;
        }

        public Criteria andHotelTypeLessThanOrEqualTo(Integer value) {
            addCriterion("hotelType <=", value, "hotelType");
            return (Criteria) this;
        }

        public Criteria andHotelTypeIn(List<Integer> values) {
            addCriterion("hotelType in", values, "hotelType");
            return (Criteria) this;
        }

        public Criteria andHotelTypeNotIn(List<Integer> values) {
            addCriterion("hotelType not in", values, "hotelType");
            return (Criteria) this;
        }

        public Criteria andHotelTypeBetween(Integer value1, Integer value2) {
            addCriterion("hotelType between", value1, value2, "hotelType");
            return (Criteria) this;
        }

        public Criteria andHotelTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("hotelType not between", value1, value2, "hotelType");
            return (Criteria) this;
        }

        public Criteria andHotelLevelIsNull() {
            addCriterion("hotelLevel is null");
            return (Criteria) this;
        }

        public Criteria andHotelLevelIsNotNull() {
            addCriterion("hotelLevel is not null");
            return (Criteria) this;
        }

        public Criteria andHotelLevelEqualTo(Integer value) {
            addCriterion("hotelLevel =", value, "hotelLevel");
            return (Criteria) this;
        }

        public Criteria andHotelLevelNotEqualTo(Integer value) {
            addCriterion("hotelLevel <>", value, "hotelLevel");
            return (Criteria) this;
        }

        public Criteria andHotelLevelGreaterThan(Integer value) {
            addCriterion("hotelLevel >", value, "hotelLevel");
            return (Criteria) this;
        }

        public Criteria andHotelLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("hotelLevel >=", value, "hotelLevel");
            return (Criteria) this;
        }

        public Criteria andHotelLevelLessThan(Integer value) {
            addCriterion("hotelLevel <", value, "hotelLevel");
            return (Criteria) this;
        }

        public Criteria andHotelLevelLessThanOrEqualTo(Integer value) {
            addCriterion("hotelLevel <=", value, "hotelLevel");
            return (Criteria) this;
        }

        public Criteria andHotelLevelIn(List<Integer> values) {
            addCriterion("hotelLevel in", values, "hotelLevel");
            return (Criteria) this;
        }

        public Criteria andHotelLevelNotIn(List<Integer> values) {
            addCriterion("hotelLevel not in", values, "hotelLevel");
            return (Criteria) this;
        }

        public Criteria andHotelLevelBetween(Integer value1, Integer value2) {
            addCriterion("hotelLevel between", value1, value2, "hotelLevel");
            return (Criteria) this;
        }

        public Criteria andHotelLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("hotelLevel not between", value1, value2, "hotelLevel");
            return (Criteria) this;
        }

        public Criteria andIsGroupPurchaseIsNull() {
            addCriterion("isGroupPurchase is null");
            return (Criteria) this;
        }

        public Criteria andIsGroupPurchaseIsNotNull() {
            addCriterion("isGroupPurchase is not null");
            return (Criteria) this;
        }

        public Criteria andIsGroupPurchaseEqualTo(Integer value) {
            addCriterion("isGroupPurchase =", value, "isGroupPurchase");
            return (Criteria) this;
        }

        public Criteria andIsGroupPurchaseNotEqualTo(Integer value) {
            addCriterion("isGroupPurchase <>", value, "isGroupPurchase");
            return (Criteria) this;
        }

        public Criteria andIsGroupPurchaseGreaterThan(Integer value) {
            addCriterion("isGroupPurchase >", value, "isGroupPurchase");
            return (Criteria) this;
        }

        public Criteria andIsGroupPurchaseGreaterThanOrEqualTo(Integer value) {
            addCriterion("isGroupPurchase >=", value, "isGroupPurchase");
            return (Criteria) this;
        }

        public Criteria andIsGroupPurchaseLessThan(Integer value) {
            addCriterion("isGroupPurchase <", value, "isGroupPurchase");
            return (Criteria) this;
        }

        public Criteria andIsGroupPurchaseLessThanOrEqualTo(Integer value) {
            addCriterion("isGroupPurchase <=", value, "isGroupPurchase");
            return (Criteria) this;
        }

        public Criteria andIsGroupPurchaseIn(List<Integer> values) {
            addCriterion("isGroupPurchase in", values, "isGroupPurchase");
            return (Criteria) this;
        }

        public Criteria andIsGroupPurchaseNotIn(List<Integer> values) {
            addCriterion("isGroupPurchase not in", values, "isGroupPurchase");
            return (Criteria) this;
        }

        public Criteria andIsGroupPurchaseBetween(Integer value1, Integer value2) {
            addCriterion("isGroupPurchase between", value1, value2, "isGroupPurchase");
            return (Criteria) this;
        }

        public Criteria andIsGroupPurchaseNotBetween(Integer value1, Integer value2) {
            addCriterion("isGroupPurchase not between", value1, value2, "isGroupPurchase");
            return (Criteria) this;
        }

        public Criteria andMinPriceIsNull() {
            addCriterion("minPrice is null");
            return (Criteria) this;
        }

        public Criteria andMinPriceIsNotNull() {
            addCriterion("minPrice is not null");
            return (Criteria) this;
        }

        public Criteria andMinPriceEqualTo(Long value) {
            addCriterion("minPrice =", value, "minPrice");
            return (Criteria) this;
        }

        public Criteria andMinPriceNotEqualTo(Long value) {
            addCriterion("minPrice <>", value, "minPrice");
            return (Criteria) this;
        }

        public Criteria andMinPriceGreaterThan(Long value) {
            addCriterion("minPrice >", value, "minPrice");
            return (Criteria) this;
        }

        public Criteria andMinPriceGreaterThanOrEqualTo(Long value) {
            addCriterion("minPrice >=", value, "minPrice");
            return (Criteria) this;
        }

        public Criteria andMinPriceLessThan(Long value) {
            addCriterion("minPrice <", value, "minPrice");
            return (Criteria) this;
        }

        public Criteria andMinPriceLessThanOrEqualTo(Long value) {
            addCriterion("minPrice <=", value, "minPrice");
            return (Criteria) this;
        }

        public Criteria andMinPriceIn(List<Long> values) {
            addCriterion("minPrice in", values, "minPrice");
            return (Criteria) this;
        }

        public Criteria andMinPriceNotIn(List<Long> values) {
            addCriterion("minPrice not in", values, "minPrice");
            return (Criteria) this;
        }

        public Criteria andMinPriceBetween(Long value1, Long value2) {
            addCriterion("minPrice between", value1, value2, "minPrice");
            return (Criteria) this;
        }

        public Criteria andMinPriceNotBetween(Long value1, Long value2) {
            addCriterion("minPrice not between", value1, value2, "minPrice");
            return (Criteria) this;
        }

        public Criteria andMaxPriceIsNull() {
            addCriterion("maxPrice is null");
            return (Criteria) this;
        }

        public Criteria andMaxPriceIsNotNull() {
            addCriterion("maxPrice is not null");
            return (Criteria) this;
        }

        public Criteria andMaxPriceEqualTo(Long value) {
            addCriterion("maxPrice =", value, "maxPrice");
            return (Criteria) this;
        }

        public Criteria andMaxPriceNotEqualTo(Long value) {
            addCriterion("maxPrice <>", value, "maxPrice");
            return (Criteria) this;
        }

        public Criteria andMaxPriceGreaterThan(Long value) {
            addCriterion("maxPrice >", value, "maxPrice");
            return (Criteria) this;
        }

        public Criteria andMaxPriceGreaterThanOrEqualTo(Long value) {
            addCriterion("maxPrice >=", value, "maxPrice");
            return (Criteria) this;
        }

        public Criteria andMaxPriceLessThan(Long value) {
            addCriterion("maxPrice <", value, "maxPrice");
            return (Criteria) this;
        }

        public Criteria andMaxPriceLessThanOrEqualTo(Long value) {
            addCriterion("maxPrice <=", value, "maxPrice");
            return (Criteria) this;
        }

        public Criteria andMaxPriceIn(List<Long> values) {
            addCriterion("maxPrice in", values, "maxPrice");
            return (Criteria) this;
        }

        public Criteria andMaxPriceNotIn(List<Long> values) {
            addCriterion("maxPrice not in", values, "maxPrice");
            return (Criteria) this;
        }

        public Criteria andMaxPriceBetween(Long value1, Long value2) {
            addCriterion("maxPrice between", value1, value2, "maxPrice");
            return (Criteria) this;
        }

        public Criteria andMaxPriceNotBetween(Long value1, Long value2) {
            addCriterion("maxPrice not between", value1, value2, "maxPrice");
            return (Criteria) this;
        }

        public Criteria andHotelStoreIsNull() {
            addCriterion("hotelStore is null");
            return (Criteria) this;
        }

        public Criteria andHotelStoreIsNotNull() {
            addCriterion("hotelStore is not null");
            return (Criteria) this;
        }

        public Criteria andHotelStoreEqualTo(Integer value) {
            addCriterion("hotelStore =", value, "hotelStore");
            return (Criteria) this;
        }

        public Criteria andHotelStoreNotEqualTo(Integer value) {
            addCriterion("hotelStore <>", value, "hotelStore");
            return (Criteria) this;
        }

        public Criteria andHotelStoreGreaterThan(Integer value) {
            addCriterion("hotelStore >", value, "hotelStore");
            return (Criteria) this;
        }

        public Criteria andHotelStoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("hotelStore >=", value, "hotelStore");
            return (Criteria) this;
        }

        public Criteria andHotelStoreLessThan(Integer value) {
            addCriterion("hotelStore <", value, "hotelStore");
            return (Criteria) this;
        }

        public Criteria andHotelStoreLessThanOrEqualTo(Integer value) {
            addCriterion("hotelStore <=", value, "hotelStore");
            return (Criteria) this;
        }

        public Criteria andHotelStoreIn(List<Integer> values) {
            addCriterion("hotelStore in", values, "hotelStore");
            return (Criteria) this;
        }

        public Criteria andHotelStoreNotIn(List<Integer> values) {
            addCriterion("hotelStore not in", values, "hotelStore");
            return (Criteria) this;
        }

        public Criteria andHotelStoreBetween(Integer value1, Integer value2) {
            addCriterion("hotelStore between", value1, value2, "hotelStore");
            return (Criteria) this;
        }

        public Criteria andHotelStoreNotBetween(Integer value1, Integer value2) {
            addCriterion("hotelStore not between", value1, value2, "hotelStore");
            return (Criteria) this;
        }

        public Criteria andCreationDateIsNull() {
            addCriterion("creationDate is null");
            return (Criteria) this;
        }

        public Criteria andCreationDateIsNotNull() {
            addCriterion("creationDate is not null");
            return (Criteria) this;
        }

        public Criteria andCreationDateEqualTo(Date value) {
            addCriterion("creationDate =", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateNotEqualTo(Date value) {
            addCriterion("creationDate <>", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateGreaterThan(Date value) {
            addCriterion("creationDate >", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateGreaterThanOrEqualTo(Date value) {
            addCriterion("creationDate >=", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateLessThan(Date value) {
            addCriterion("creationDate <", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateLessThanOrEqualTo(Date value) {
            addCriterion("creationDate <=", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateIn(List<Date> values) {
            addCriterion("creationDate in", values, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateNotIn(List<Date> values) {
            addCriterion("creationDate not in", values, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateBetween(Date value1, Date value2) {
            addCriterion("creationDate between", value1, value2, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateNotBetween(Date value1, Date value2) {
            addCriterion("creationDate not between", value1, value2, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("createdBy is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("createdBy is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(Long value) {
            addCriterion("createdBy =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(Long value) {
            addCriterion("createdBy <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(Long value) {
            addCriterion("createdBy >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(Long value) {
            addCriterion("createdBy >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(Long value) {
            addCriterion("createdBy <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(Long value) {
            addCriterion("createdBy <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<Long> values) {
            addCriterion("createdBy in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<Long> values) {
            addCriterion("createdBy not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(Long value1, Long value2) {
            addCriterion("createdBy between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(Long value1, Long value2) {
            addCriterion("createdBy not between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andModifyDateIsNull() {
            addCriterion("modifyDate is null");
            return (Criteria) this;
        }

        public Criteria andModifyDateIsNotNull() {
            addCriterion("modifyDate is not null");
            return (Criteria) this;
        }

        public Criteria andModifyDateEqualTo(Date value) {
            addCriterion("modifyDate =", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotEqualTo(Date value) {
            addCriterion("modifyDate <>", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateGreaterThan(Date value) {
            addCriterion("modifyDate >", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateGreaterThanOrEqualTo(Date value) {
            addCriterion("modifyDate >=", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateLessThan(Date value) {
            addCriterion("modifyDate <", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateLessThanOrEqualTo(Date value) {
            addCriterion("modifyDate <=", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateIn(List<Date> values) {
            addCriterion("modifyDate in", values, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotIn(List<Date> values) {
            addCriterion("modifyDate not in", values, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateBetween(Date value1, Date value2) {
            addCriterion("modifyDate between", value1, value2, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotBetween(Date value1, Date value2) {
            addCriterion("modifyDate not between", value1, value2, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifiedByIsNull() {
            addCriterion("modifiedBy is null");
            return (Criteria) this;
        }

        public Criteria andModifiedByIsNotNull() {
            addCriterion("modifiedBy is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedByEqualTo(Long value) {
            addCriterion("modifiedBy =", value, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andModifiedByNotEqualTo(Long value) {
            addCriterion("modifiedBy <>", value, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andModifiedByGreaterThan(Long value) {
            addCriterion("modifiedBy >", value, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andModifiedByGreaterThanOrEqualTo(Long value) {
            addCriterion("modifiedBy >=", value, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andModifiedByLessThan(Long value) {
            addCriterion("modifiedBy <", value, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andModifiedByLessThanOrEqualTo(Long value) {
            addCriterion("modifiedBy <=", value, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andModifiedByIn(List<Long> values) {
            addCriterion("modifiedBy in", values, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andModifiedByNotIn(List<Long> values) {
            addCriterion("modifiedBy not in", values, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andModifiedByBetween(Long value1, Long value2) {
            addCriterion("modifiedBy between", value1, value2, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andModifiedByNotBetween(Long value1, Long value2) {
            addCriterion("modifiedBy not between", value1, value2, "modifiedBy");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table itrip_hotel
     *
     * @mbggenerated do_not_delete_during_merge Tue Apr 25 11:19:39 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table itrip_hotel
     *
     * @mbggenerated Tue Apr 25 11:19:39 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}